export interface Wilaya {
  code: string
  nameFr: string
  nameAr: string
}

export interface Commune {
  nameFr: string
  nameAr: string
}

export const WILAYAS: Wilaya[] = [
  { code: '01', nameFr: 'Adrar', nameAr: 'أدرار' },
  { code: '02', nameFr: 'Chlef', nameAr: 'الشلف' },
  { code: '03', nameFr: 'Laghouat', nameAr: 'الأغواط' },
  { code: '04', nameFr: 'Oum El Bouaghi', nameAr: 'أم البواقي' },
  { code: '05', nameFr: 'Batna', nameAr: 'باتنة' },
  { code: '06', nameFr: 'Béjaïa', nameAr: 'بجاية' },
  { code: '07', nameFr: 'Biskra', nameAr: 'بسكرة' },
  { code: '08', nameFr: 'Béchar', nameAr: 'بشار' },
  { code: '09', nameFr: 'Blida', nameAr: 'البليدة' },
  { code: '10', nameFr: 'Bouira', nameAr: 'البويرة' },
  { code: '11', nameFr: 'Tamanrasset', nameAr: 'تمنراست' },
  { code: '12', nameFr: 'Tébessa', nameAr: 'تبسة' },
  { code: '13', nameFr: 'Tlemcen', nameAr: 'تلمسان' },
  { code: '14', nameFr: 'Tiaret', nameAr: 'تيارت' },
  { code: '15', nameFr: 'Tizi Ouzou', nameAr: 'تيزي وزو' },
  { code: '16', nameFr: 'Alger', nameAr: 'الجزائر' },
  { code: '17', nameFr: 'Djelfa', nameAr: 'الجلفة' },
  { code: '18', nameFr: 'Jijel', nameAr: 'جيجل' },
  { code: '19', nameFr: 'Sétif', nameAr: 'سطيف' },
  { code: '20', nameFr: 'Saïda', nameAr: 'سعيدة' },
  { code: '21', nameFr: 'Skikda', nameAr: 'سكيكدة' },
  { code: '22', nameFr: 'Sidi Bel Abbès', nameAr: 'سيدي بلعباس' },
  { code: '23', nameFr: 'Annaba', nameAr: 'عنابة' },
  { code: '24', nameFr: 'Guelma', nameAr: 'قالمة' },
  { code: '25', nameFr: 'Constantine', nameAr: 'قسنطينة' },
  { code: '26', nameFr: 'Médéa', nameAr: 'المدية' },
  { code: '27', nameFr: 'Mostaganem', nameAr: 'مستغانم' },
  { code: '28', nameFr: "M'Sila", nameAr: 'المسيلة' },
  { code: '29', nameFr: 'Mascara', nameAr: 'معسكر' },
  { code: '30', nameFr: 'Ouargla', nameAr: 'ورقلة' },
  { code: '31', nameFr: 'Oran', nameAr: 'وهران' },
  { code: '32', nameFr: 'El Bayadh', nameAr: 'البيض' },
  { code: '33', nameFr: 'Illizi', nameAr: 'إليزي' },
  { code: '34', nameFr: 'Bordj Bou Arréridj', nameAr: 'برج بوعريريج' },
  { code: '35', nameFr: 'Boumerdès', nameAr: 'بومرداس' },
  { code: '36', nameFr: 'El Tarf', nameAr: 'الطارف' },
  { code: '37', nameFr: 'Tindouf', nameAr: 'تندوف' },
  { code: '38', nameFr: 'Tissemsilt', nameAr: 'تيسمسيلت' },
  { code: '39', nameFr: 'El Oued', nameAr: 'الوادي' },
  { code: '40', nameFr: 'Khenchela', nameAr: 'خنشلة' },
  { code: '41', nameFr: 'Souk Ahras', nameAr: 'سوق أهراس' },
  { code: '42', nameFr: 'Tipaza', nameAr: 'تيبازة' },
  { code: '43', nameFr: 'Mila', nameAr: 'ميلة' },
  { code: '44', nameFr: 'Aïn Defla', nameAr: 'عين الدفلى' },
  { code: '45', nameFr: 'Naâma', nameAr: 'النعامة' },
  { code: '46', nameFr: 'Aïn Témouchent', nameAr: 'عين تيموشنت' },
  { code: '47', nameFr: 'Ghardaïa', nameAr: 'غرداية' },
  { code: '48', nameFr: 'Relizane', nameAr: 'غليزان' },
  { code: '49', nameFr: 'Timimoun', nameAr: 'تيميمون' },
  { code: '50', nameFr: 'Bordj Badji Mokhtar', nameAr: 'برج باجي مختار' },
  { code: '51', nameFr: 'Ouled Djellal', nameAr: 'أولاد جلال' },
  { code: '52', nameFr: 'Béni Abbès', nameAr: 'بني عباس' },
  { code: '53', nameFr: 'In Salah', nameAr: 'عين صالح' },
  { code: '54', nameFr: 'In Guezzam', nameAr: 'عين قزام' },
  { code: '55', nameFr: 'Touggourt', nameAr: 'تقرت' },
  { code: '56', nameFr: 'Djanet', nameAr: 'جانت' },
  { code: '57', nameFr: "El M'Ghair", nameAr: 'المغير' },
  { code: '58', nameFr: 'El Meniaa', nameAr: 'المنيعة' },
]

export const COMMUNES: Record<string, Commune[]> = {
  '01': [
    { nameFr: "Timekten", nameAr: "تيمقتن" },
    { nameFr: "Bouda", nameAr: "بودة" },
    { nameFr: "Ouled Ahmed Timmi", nameAr: "أولاد أحمد تيمي" },
    { nameFr: "Adrar", nameAr: "أدرار" },
    { nameFr: "Fenoughil", nameAr: "فنوغيل" },
    { nameFr: "In Zghmir", nameAr: "إن زغمير" },
    { nameFr: "Reggane", nameAr: "رقان" },
    { nameFr: "Sali", nameAr: "سالي" },
    { nameFr: "Sebaa", nameAr: "السبع" },
    { nameFr: "Tsabit", nameAr: "تسابيت" },
    { nameFr: "Tamest", nameAr: "تامست" },
    { nameFr: "Tamantit", nameAr: "تامنطيط" },
    { nameFr: "Tit", nameAr: "تيت" },
    { nameFr: "Zaouiet Kounta", nameAr: "زاوية كنتة" },
    { nameFr: "Akabli", nameAr: "اقبلي" },
    { nameFr: "Aoulef", nameAr: "أولف" },
  ],
  '02': [
    { nameFr: "Talassa", nameAr: "تلعصة" },
    { nameFr: "Zeboudja", nameAr: "الزبوجة" },
    { nameFr: "El Hadjadj", nameAr: "الحجاج" },
    { nameFr: "Ouled Ben Abdelkader", nameAr: "أولاد بن عبد القادر" },
    { nameFr: "Ain Merane", nameAr: "عين مران" },
    { nameFr: "Breira", nameAr: "بريرة" },
    { nameFr: "Ouled Abbes", nameAr: "أولاد عباس" },
    { nameFr: "Oued Fodda", nameAr: "وادي الفضة" },
    { nameFr: "Beni Rached", nameAr: "بني راشد" },
    { nameFr: "Herenfa", nameAr: "الهرانفة" },
    { nameFr: "Tadjena", nameAr: "تاجنة" },
    { nameFr: "El Marsa", nameAr: "المرسى" },
    { nameFr: "Chlef", nameAr: "الشلف" },
    { nameFr: "Oum Drou", nameAr: "أم الدروع" },
    { nameFr: "Sendjas", nameAr: "سنجاس" },
    { nameFr: "Sidi Abderrahmane", nameAr: "سيدي عبد الرحمن" },
    { nameFr: "Sidi Akkacha", nameAr: "سيدي عكاشة" },
    { nameFr: "Tenes", nameAr: "تنس" },
    { nameFr: "Beni  Bouattab", nameAr: "بني بوعتاب" },
    { nameFr: "El Karimia", nameAr: "الكريمية" },
    { nameFr: "Harchoun", nameAr: "حرشون" },
    { nameFr: "Bouzeghaia", nameAr: "بوزغاية" },
    { nameFr: "Taougrit", nameAr: "تاوقريت" },
    { nameFr: "Beni Haoua", nameAr: "بني حواء" },
    { nameFr: "Abou El Hassane", nameAr: "أبو الحسن" },
    { nameFr: "Oued Goussine", nameAr: "وادي قوسين" },
    { nameFr: "Chettia", nameAr: "الشطية" },
    { nameFr: "Moussadek", nameAr: "مصدق" },
    { nameFr: "Ouled Fares", nameAr: "أولاد فارس" },
    { nameFr: "Boukadir", nameAr: "بوقادير" },
    { nameFr: "Oued Sly", nameAr: "وادي سلي" },
    { nameFr: "Sobha", nameAr: "الصبحة" },
    { nameFr: "Benairia", nameAr: "بنايرية" },
    { nameFr: "Labiod Medjadja", nameAr: "الأبيض مجاجة" },
    { nameFr: "Dahra", nameAr: "الظهرة" },
  ],
  '03': [
    { nameFr: "El Beidha", nameAr: "البيضاء" },
    { nameFr: "Gueltat Sidi Saad", nameAr: "قلتة سيدي سعد" },
    { nameFr: "Brida", nameAr: "بريدة" },
    { nameFr: "Ain Sidi Ali", nameAr: "عين سيدي علي" },
    { nameFr: "Tadjemout", nameAr: "تاجموت" },
    { nameFr: "Hadj Mechri", nameAr: "الحاج مشري" },
    { nameFr: "Taouiala", nameAr: "تاويالة" },
    { nameFr: "El Ghicha", nameAr: "الغيشة" },
    { nameFr: "Tadjrouna", nameAr: "تاجرونة" },
    { nameFr: "Sebgag", nameAr: "سبقاق" },
    { nameFr: "Sidi Bouzid", nameAr: "سيدي بوزيد" },
    { nameFr: "Oued Morra", nameAr: "وادي مرة" },
    { nameFr: "Laghouat", nameAr: "الأغواط" },
    { nameFr: "Oued M'zi", nameAr: "وادي مزي" },
    { nameFr: "Ksar El Hirane", nameAr: "قصر الحيران" },
    { nameFr: "El Assafia", nameAr: "العسافية" },
    { nameFr: "Sidi Makhlouf", nameAr: "سيدي مخلوف" },
    { nameFr: "Hassi Delaa", nameAr: "حاسي الدلاعة" },
    { nameFr: "Hassi R'mel", nameAr: "حاسي الرمل" },
    { nameFr: "Ain Madhi", nameAr: "عين ماضي" },
    { nameFr: "El Haouaita", nameAr: "الحويطة" },
    { nameFr: "Kheneg", nameAr: "الخنق" },
    { nameFr: "Benacer Benchohra", nameAr: "بن ناصر بن شهرة" },
    { nameFr: "Aflou", nameAr: "أفلو" },
  ],
  '04': [
    { nameFr: "Fkirina", nameAr: "فكيرينة" },
    { nameFr: "El Fedjoudj Boughrara Sa", nameAr: "الفجوج بوغرارة سعودي" },
    { nameFr: "Ain Fekroun", nameAr: "عين فكرون" },
    { nameFr: "Rahia", nameAr: "الرحية" },
    { nameFr: "Meskiana", nameAr: "مسكيانة" },
    { nameFr: "El Belala", nameAr: "البلالة" },
    { nameFr: "Behir Chergui", nameAr: "بحير الشرقي" },
    { nameFr: "Ksar Sbahi", nameAr: "قصر الصباحي" },
    { nameFr: "Souk Naamane", nameAr: "سوق نعمان" },
    { nameFr: "Ouled Zouai", nameAr: "أولاد زواي" },
    { nameFr: "Oum El Bouaghi", nameAr: "أم البواقي" },
    { nameFr: "Ain Babouche", nameAr: "عين ببوش" },
    { nameFr: "Ain Zitoun", nameAr: "عين الزيتون" },
    { nameFr: "Bir Chouhada", nameAr: "بئر الشهداء" },
    { nameFr: "Ain Beida", nameAr: "عين البيضاء" },
    { nameFr: "Berriche", nameAr: "بريش" },
    { nameFr: "Zorg", nameAr: "الزرق" },
    { nameFr: "Ain M'lila", nameAr: "عين مليلة" },
    { nameFr: "Ouled Gacem", nameAr: "أولاد قاسم" },
    { nameFr: "Ouled Hamla", nameAr: "أولاد حملة" },
    { nameFr: "El Amiria", nameAr: "العامرية" },
    { nameFr: "Sigus", nameAr: "سيقوس" },
    { nameFr: "Oued Nini", nameAr: "وادي نيني" },
    { nameFr: "Ain Diss", nameAr: "عين الديس" },
    { nameFr: "Dhalaa", nameAr: "الضلعة" },
    { nameFr: "El Djazia", nameAr: "الجازية" },
    { nameFr: "Ain Kercha", nameAr: "عين كرشة" },
    { nameFr: "El Harmilia", nameAr: "الحرملية" },
    { nameFr: "Hanchir Toumghani", nameAr: "هنشير تومغني" },
  ],
  '05': [
    { nameFr: "Maafa", nameAr: "معافة" },
    { nameFr: "Gosbat", nameAr: "القصبات" },
    { nameFr: "Timgad", nameAr: "تيمقاد" },
    { nameFr: "Taxlent", nameAr: "تاكسلانت" },
    { nameFr: "Ouled Si Slimane", nameAr: "أولاد سي سليمان" },
    { nameFr: "Lemcene", nameAr: "لمسان" },
    { nameFr: "Talkhamt", nameAr: "تالخمت" },
    { nameFr: "Ras El Aioun", nameAr: "رأس العيون" },
    { nameFr: "Rahbat", nameAr: "الرحبات" },
    { nameFr: "Ouled Sellem", nameAr: "أولاد سلام" },
    { nameFr: "Guigba", nameAr: "القيقبة" },
    { nameFr: "Teniet El Abed", nameAr: "ثنية العابد" },
    { nameFr: "Batna", nameAr: "باتنة" },
    { nameFr: "Fesdis", nameAr: "فسديس" },
    { nameFr: "Oued Chaaba", nameAr: "وادي الشعبة" },
    { nameFr: "Hidoussa", nameAr: "حيدوسة" },
    { nameFr: "Ksar Bellezma", nameAr: "قصر بلزمة" },
    { nameFr: "Merouana", nameAr: "مروانة" },
    { nameFr: "Oued El Ma", nameAr: "وادي الماء" },
    { nameFr: "Lazrou", nameAr: "لازرو" },
    { nameFr: "Seriana", nameAr: "سريانة" },
    { nameFr: "Zanet El Beida", nameAr: "زانة البيضاء" },
    { nameFr: "Menaa", nameAr: "منعة" },
    { nameFr: "Tigharghar", nameAr: "تغرغار" },
    { nameFr: "Ain Yagout", nameAr: "عين ياقوت" },
    { nameFr: "Boumia", nameAr: "بومية" },
    { nameFr: "Djerma", nameAr: "جرمة" },
    { nameFr: "El Madher", nameAr: "المعذر" },
    { nameFr: "Ouyoun El Assafir", nameAr: "عيون العصافير" },
    { nameFr: "Tazoult", nameAr: "تازولت" },
    { nameFr: "Boumagueur", nameAr: "بومقر" },
    { nameFr: "N Gaous", nameAr: "نقاوس" },
    { nameFr: "Sefiane", nameAr: "سفيان" },
    { nameFr: "Arris", nameAr: "أريس" },
    { nameFr: "Tighanimine", nameAr: "تيغانمين" },
    { nameFr: "Ain Djasser", nameAr: "عين جاسر" },
    { nameFr: "El Hassi", nameAr: "الحاسي" },
    { nameFr: "Seggana", nameAr: "سقانة" },
    { nameFr: "Tilatou", nameAr: "تيلاطو" },
    { nameFr: "Foum Toub", nameAr: "فم الطوب" },
    { nameFr: "Ichemoul", nameAr: "إشمول" },
    { nameFr: "Inoughissen", nameAr: "إينوغيسن" },
    { nameFr: "Bouzina", nameAr: "بوزينة" },
    { nameFr: "Larbaa", nameAr: "لارباع" },
    { nameFr: "Boulhilat", nameAr: "بولهيلات" },
    { nameFr: "Chemora", nameAr: "الشمرة" },
    { nameFr: "Barika", nameAr: "بريكة" },
    { nameFr: "Bitam", nameAr: "بيطام" },
    { nameFr: "M Doukal", nameAr: "إمدوكل" },
    { nameFr: "Azil Abedelkader", nameAr: "عزيل عبد القادر" },
    { nameFr: "Djezzar", nameAr: "الجزار" },
    { nameFr: "Ouled Ammar", nameAr: "أولاد عمار" },
    { nameFr: "Ghassira", nameAr: "غسيرة" },
    { nameFr: "Kimmel", nameAr: "كيمل" },
    { nameFr: "T Kout", nameAr: "تكوت" },
    { nameFr: "Ain Touta", nameAr: "عين التوتة" },
    { nameFr: "Beni Foudhala El Hakania", nameAr: "بني فضالة الحقانية" },
    { nameFr: "Ouled Fadel", nameAr: "أولاد فاضل" },
    { nameFr: "Ouled Aouf", nameAr: "أولاد عوف" },
    { nameFr: "Chir", nameAr: "شير" },
    { nameFr: "Oued Taga", nameAr: "وادي الطاقة" },
  ],
  '06': [
    { nameFr: "Sidi Ayad", nameAr: "سيدي عياد" },
    { nameFr: "Barbacha", nameAr: "برباشة" },
    { nameFr: "Leflaye", nameAr: "الفلاي" },
    { nameFr: "Kendira", nameAr: "كنديرة" },
    { nameFr: "Sidi-Aich", nameAr: "سيدي عيش" },
    { nameFr: "Tifra", nameAr: "تيفرة" },
    { nameFr: "Tinebdar", nameAr: "تينبدار" },
    { nameFr: "El Kseur", nameAr: "القصر" },
    { nameFr: "Fenaia Il Maten", nameAr: "فناية الماثن" },
    { nameFr: "Toudja", nameAr: "توجة" },
    { nameFr: "Dra El Caid", nameAr: "ذراع القايد" },
    { nameFr: "Kherrata", nameAr: "خراطة" },
    { nameFr: "Bejaia", nameAr: "بجاية" },
    { nameFr: "Oued Ghir", nameAr: "وادي غير" },
    { nameFr: "Benimaouche", nameAr: "بني معوش" },
    { nameFr: "Beni Djellil", nameAr: "بني جليل" },
    { nameFr: "Feraoun", nameAr: "فرعون" },
    { nameFr: "Smaoun", nameAr: "سمعون" },
    { nameFr: "Timezrit", nameAr: "تيمزريت" },
    { nameFr: "Melbou", nameAr: "مالبو" },
    { nameFr: "Souk El Tenine", nameAr: "سوق لإثنين" },
    { nameFr: "Tamridjet", nameAr: "تامريجت" },
    { nameFr: "Boukhelifa", nameAr: "بوخليفة" },
    { nameFr: "Tala Hamza", nameAr: "تالة حمزة" },
    { nameFr: "Tichy", nameAr: "تيشي" },
    { nameFr: "Ait R'zine", nameAr: "أيت رزين" },
    { nameFr: "Ighil-Ali", nameAr: "إغيل علي" },
    { nameFr: "Ait-Smail", nameAr: "أيت إسماعيل" },
    { nameFr: "Darguina", nameAr: "درقينة" },
    { nameFr: "Taskriout", nameAr: "تاسكريوت" },
    { nameFr: "Aokas", nameAr: "أوقاس" },
    { nameFr: "Tizi-N'berber", nameAr: "تيزي نبربر" },
    { nameFr: "Adekar", nameAr: "أدكار" },
    { nameFr: "Beni K'sila", nameAr: "بني كسيلة" },
    { nameFr: "Taourit Ighil", nameAr: "تاوريرت إغيل" },
    { nameFr: "Akbou", nameAr: "أقبو" },
    { nameFr: "Chellata", nameAr: "شلاطة" },
    { nameFr: "Ighram", nameAr: "اغرم" },
    { nameFr: "Tamokra", nameAr: "تامقرة" },
    { nameFr: "Amalou", nameAr: "أمالو" },
    { nameFr: "Bouhamza", nameAr: "بوحمزة" },
    { nameFr: "M'cisna", nameAr: "مسيسنة" },
    { nameFr: "Seddouk", nameAr: "صدوق" },
    { nameFr: "Beni-Mallikeche", nameAr: "بني مليكش" },
    { nameFr: "Boudjellil", nameAr: "بو جليل" },
    { nameFr: "Tazmalt", nameAr: "تازمالت" },
    { nameFr: "Akfadou", nameAr: "أكفادو" },
    { nameFr: "Chemini", nameAr: "شميني" },
    { nameFr: "Souk Oufella", nameAr: "سوق اوفلا" },
    { nameFr: "Tibane", nameAr: "طيبان" },
    { nameFr: "Ouzellaguen", nameAr: "أوزلاقن" },
    { nameFr: "Amizour", nameAr: "أميزور" },
  ],
  '07': [
    { nameFr: "El Feidh", nameAr: "الفيض" },
    { nameFr: "Lichana", nameAr: "ليشانة" },
    { nameFr: "Bouchakroun", nameAr: "بوشقرون" },
    { nameFr: "Mekhadma", nameAr: "مخادمة" },
    { nameFr: "Djemorah", nameAr: "جمورة" },
    { nameFr: "Branis", nameAr: "برانيس" },
    { nameFr: "El Outaya", nameAr: "الوطاية" },
    { nameFr: "El Kantara", nameAr: "القنطرة" },
    { nameFr: "Khenguet Sidi Nadji", nameAr: "خنقة سيدي ناجي" },
    { nameFr: "Ain Zaatout", nameAr: "عين زعطوط" },
    { nameFr: "Zeribet El Oued", nameAr: "زريبة الوادي" },
    { nameFr: "Meziraa", nameAr: "المزيرعة" },
    { nameFr: "Biskra", nameAr: "بسكرة" },
    { nameFr: "El Hadjab", nameAr: "الحاجب" },
    { nameFr: "M'lili", nameAr: "مليلي" },
    { nameFr: "Foughala", nameAr: "فوغالة" },
    { nameFr: "El Ghrous", nameAr: "الغروس" },
    { nameFr: "Bordj Ben Azzouz", nameAr: "برج بن عزوز" },
    { nameFr: "Ourlal", nameAr: "أورلال" },
    { nameFr: "Oumache", nameAr: "أوماش" },
    { nameFr: "Ain Naga", nameAr: "عين الناقة" },
    { nameFr: "Chetma", nameAr: "شتمة" },
    { nameFr: "El Haouch", nameAr: "الحوش" },
    { nameFr: "Sidi Okba", nameAr: "سيدي عقبة" },
    { nameFr: "M'chouneche", nameAr: "مشونش" },
    { nameFr: "Lioua", nameAr: "ليوة" },
    { nameFr: "Tolga", nameAr: "طولقة" },
  ],
  '08': [
    { nameFr: "Bechar", nameAr: "بشار" },
    { nameFr: "Boukais", nameAr: "بوكايس" },
    { nameFr: "Lahmar", nameAr: "لحمر" },
    { nameFr: "Mogheul", nameAr: "موغل" },
    { nameFr: "Meridja", nameAr: "المريجة" },
    { nameFr: "Taghit", nameAr: "تاغيت" },
    { nameFr: "Abadla", nameAr: "العبادلة" },
    { nameFr: "Erg-Ferradj", nameAr: "عرق فراج" },
    { nameFr: "Machraa-Houari-Boumediene", nameAr: "مشرع هواري بومدين" },
    { nameFr: "Beni-Ounif", nameAr: "بني ونيف" },
    { nameFr: "Tabelbala", nameAr: "تبلبالة" },
    { nameFr: "Kenadsa", nameAr: "القنادسة" },
  ],
  '09': [
    { nameFr: "Beni Mered", nameAr: "بني مراد" },
    { nameFr: "Ouled Slama", nameAr: "اولاد سلامة" },
    { nameFr: "Mouzaia", nameAr: "موزاية" },
    { nameFr: "Hammam Elouane", nameAr: "حمام ملوان" },
    { nameFr: "Bougara", nameAr: "بوقرة" },
    { nameFr: "Souhane", nameAr: "صوحان" },
    { nameFr: "Larbaa", nameAr: "الأربعاء" },
    { nameFr: "Soumaa", nameAr: "الصومعة" },
    { nameFr: "Guerrouaou", nameAr: "قرواو" },
    { nameFr: "Boufarik", nameAr: "بوفاريك" },
    { nameFr: "Meftah", nameAr: "مفتاح" },
    { nameFr: "Chiffa", nameAr: "الشفة" },
    { nameFr: "Ain Romana", nameAr: "عين الرمانة" },
    { nameFr: "Oued  Djer", nameAr: "وادي جر" },
    { nameFr: "El-Affroun", nameAr: "العفرون" },
    { nameFr: "Ouled Yaich", nameAr: "أولاد يعيش" },
    { nameFr: "Chrea", nameAr: "الشريعة" },
    { nameFr: "Djebabra", nameAr: "جبابرة" },
    { nameFr: "Oued El Alleug", nameAr: "وادي العلايق" },
    { nameFr: "Benkhelil", nameAr: "بن خليل" },
    { nameFr: "Beni-Tamou", nameAr: "بني تامو" },
    { nameFr: "Chebli", nameAr: "الشبلي" },
    { nameFr: "Bouinan", nameAr: "بوعينان" },
    { nameFr: "Bouarfa", nameAr: "بوعرفة" },
    { nameFr: "Blida", nameAr: "البليدة" },
  ],
  '10': [
    { nameFr: "Ain Laloui", nameAr: "عين العلوي" },
    { nameFr: "Hadjera Zerga", nameAr: "الحجرة الزرقاء" },
    { nameFr: "Mezdour", nameAr: "مزدور" },
    { nameFr: "Taguedite", nameAr: "تاقديت" },
    { nameFr: "Ridane", nameAr: "ريدان" },
    { nameFr: "Maamora", nameAr: "المعمورة" },
    { nameFr: "El-Hakimia", nameAr: "الحاكمية" },
    { nameFr: "Ahl El Ksar", nameAr: "أهل القصر" },
    { nameFr: "Dirah", nameAr: "ديرة" },
    { nameFr: "Dechmia", nameAr: "الدشمية" },
    { nameFr: "Bechloul", nameAr: "بشلول" },
    { nameFr: "Ath Mansour", nameAr: "آث  منصور" },
    { nameFr: "Saharidj", nameAr: "سحاريج" },
    { nameFr: "El Adjiba", nameAr: "العجيبة" },
    { nameFr: "El Asnam", nameAr: "الأسنام" },
    { nameFr: "M Chedallah", nameAr: "أمشدالة" },
    { nameFr: "Bordj Okhriss", nameAr: "برج أوخريص" },
    { nameFr: "Sour El Ghozlane", nameAr: "سور الغزلان" },
    { nameFr: "Hanif", nameAr: "حنيف" },
    { nameFr: "Chorfa", nameAr: "شرفة" },
    { nameFr: "Ouled Rached", nameAr: "أولاد راشد" },
    { nameFr: "Ain El Hadjar", nameAr: "عين الحجر" },
    { nameFr: "Aghbalou", nameAr: "أغبالو" },
    { nameFr: "Raouraoua", nameAr: "روراوة" },
    { nameFr: "El Khabouzia", nameAr: "الخبوزية" },
    { nameFr: "Bir Ghbalou", nameAr: "بئر غبالو" },
    { nameFr: "Bouira", nameAr: "البويرة" },
    { nameFr: "Ain Turk", nameAr: "عين الترك" },
    { nameFr: "Ait Laaziz", nameAr: "أيت لعزيز" },
    { nameFr: "Ain-Bessem", nameAr: "عين بسام" },
    { nameFr: "El-Mokrani", nameAr: "المقراني" },
    { nameFr: "Souk El Khemis", nameAr: "سوق الخميس" },
    { nameFr: "Aomar", nameAr: "أعمر" },
    { nameFr: "Djebahia", nameAr: "جباحية" },
    { nameFr: "El Hachimia", nameAr: "الهاشمية" },
    { nameFr: "Haizer", nameAr: "حيزر" },
    { nameFr: "Taghzout", nameAr: "تاغزوت" },
    { nameFr: "Bouderbala", nameAr: "بودربالة" },
    { nameFr: "Boukram", nameAr: "بوكرم" },
    { nameFr: "Guerrouma", nameAr: "قرومة" },
    { nameFr: "Lakhdaria", nameAr: "الأخضرية" },
    { nameFr: "Maala", nameAr: "معلة" },
    { nameFr: "Kadiria", nameAr: "قادرية" },
    { nameFr: "Z'barbar (El Isseri )", nameAr: "زبربر" },
    { nameFr: "Oued El Berdi", nameAr: "وادي البردي" },
  ],
  '11': [
    { nameFr: "Tazrouk", nameAr: "تاظروك" },
    { nameFr: "Abelsa", nameAr: "ابلسة" },
    { nameFr: "Tamanrasset", nameAr: "تمنراست" },
    { nameFr: "Ain Amguel", nameAr: "عين امقل" },
    { nameFr: "Idles", nameAr: "أدلس" },
  ],
  '12': [
    { nameFr: "El-Houidjbet", nameAr: "الحويجبات" },
    { nameFr: "El-Aouinet", nameAr: "العوينات" },
    { nameFr: "Ferkane", nameAr: "فركان" },
    { nameFr: "Negrine", nameAr: "نقرين" },
    { nameFr: "Bir Mokkadem", nameAr: "بئر مقدم" },
    { nameFr: "Bir Dheheb", nameAr: "بئر الذهب" },
    { nameFr: "Saf Saf El Ouesra", nameAr: "صفصاف الوسرى" },
    { nameFr: "Guorriguer", nameAr: "قريقر" },
    { nameFr: "Bekkaria", nameAr: "بكارية" },
    { nameFr: "Boulhaf Dyr", nameAr: "بولحاف الدير" },
    { nameFr: "Oum Ali", nameAr: "أم علي" },
    { nameFr: "Boukhadra", nameAr: "بوخضرة" },
    { nameFr: "El Malabiod", nameAr: "الماء الابيض" },
    { nameFr: "Ouenza", nameAr: "الونزة" },
    { nameFr: "El Meridj", nameAr: "المريج" },
    { nameFr: "Ain Zerga", nameAr: "عين الزرقاء" },
    { nameFr: "Stah Guentis", nameAr: "سطح قنطيس" },
    { nameFr: "El Ogla", nameAr: "العقلة" },
    { nameFr: "El Mezeraa", nameAr: "المزرعة" },
    { nameFr: "Bedjene", nameAr: "بجن" },
    { nameFr: "Morsott", nameAr: "مرسط" },
    { nameFr: "Telidjen", nameAr: "ثليجان" },
    { nameFr: "Cheria", nameAr: "الشريعة" },
    { nameFr: "El Ogla El Malha", nameAr: "العقلة المالحة" },
    { nameFr: "Bir-El-Ater", nameAr: "بئر العاتر" },
    { nameFr: "Tebessa", nameAr: "تبسة" },
    { nameFr: "Hammamet", nameAr: "الحمامات" },
    { nameFr: "El Kouif", nameAr: "الكويف" },
  ],
  '13': [
    { nameFr: "Bab El Assa", nameAr: "باب العسة" },
    { nameFr: "Terny Beni Hediel", nameAr: "تيرني بني هديل" },
    { nameFr: "Mansourah", nameAr: "منصورة" },
    { nameFr: "Beni Mester", nameAr: "بني مستر" },
    { nameFr: "Ain Ghoraba", nameAr: "عين غرابة" },
    { nameFr: "Chetouane", nameAr: "شتوان" },
    { nameFr: "Amieur", nameAr: "عمير" },
    { nameFr: "Ain Fezza", nameAr: "عين فزة" },
    { nameFr: "Honnaine", nameAr: "هنين" },
    { nameFr: "Beni Khellad", nameAr: "بني خلاد" },
    { nameFr: "Sidi Djillali", nameAr: "سيدي الجيلالي" },
    { nameFr: "Bouihi", nameAr: "البويهي" },
    { nameFr: "Nedroma", nameAr: "ندرومة" },
    { nameFr: "M'sirda Fouaga", nameAr: "مسيردة الفواقة" },
    { nameFr: "Marsa Ben M'hidi", nameAr: "مرسى بن مهيدي" },
    { nameFr: "Sidi Medjahed", nameAr: "سيدي مجاهد" },
    { nameFr: "Beni Boussaid", nameAr: "بني بوسعيد" },
    { nameFr: "Sebdou", nameAr: "سبدو" },
    { nameFr: "El Gor", nameAr: "القور" },
    { nameFr: "El Aricha", nameAr: "العريشة" },
    { nameFr: "Bouhlou", nameAr: "بوحلو" },
    { nameFr: "Maghnia", nameAr: "مغنية" },
    { nameFr: "Hammam Boughrara", nameAr: "حمام بوغرارة" },
    { nameFr: "Zenata", nameAr: "زناتة" },
    { nameFr: "Ouled Riyah", nameAr: "أولاد رياح" },
    { nameFr: "Hennaya", nameAr: "الحناية" },
    { nameFr: "Sidi Abdelli", nameAr: "سيدي العبدلي" },
    { nameFr: "Souk Tleta", nameAr: "سوق الثلاثاء" },
    { nameFr: "Bensekrane", nameAr: "بن سكران" },
    { nameFr: "Fellaoucene", nameAr: "فلاوسن" },
    { nameFr: "Ain Kebira", nameAr: "عين الكبيرة" },
    { nameFr: "Ain Fetah", nameAr: "عين فتاح" },
    { nameFr: "Tlemcen", nameAr: "تلمسان" },
    { nameFr: "Ain Nehala", nameAr: "عين النحالة" },
    { nameFr: "Ain Tellout", nameAr: "عين تالوت" },
    { nameFr: "Ain Youcef", nameAr: "عين يوسف" },
    { nameFr: "Beni Ouarsous", nameAr: "بني وارسوس" },
    { nameFr: "El Fehoul", nameAr: "الفحول" },
    { nameFr: "Remchi", nameAr: "الرمشي" },
    { nameFr: "Sebbaa Chioukh", nameAr: "سبعة شيوخ" },
    { nameFr: "Souani", nameAr: "السواني" },
    { nameFr: "Sabra", nameAr: "صبرة" },
    { nameFr: "Dar Yaghmoracen", nameAr: "دار يغمراسن" },
    { nameFr: "Ghazaouet", nameAr: "الغزوات" },
    { nameFr: "Souahlia", nameAr: "السواحلية" },
    { nameFr: "Tianet", nameAr: "تيانت" },
    { nameFr: "Beni Smiel", nameAr: "بني صميل" },
    { nameFr: "Oued Lakhdar", nameAr: "وادي الخضر" },
    { nameFr: "Ouled Mimoun", nameAr: "أولاد ميمون" },
    { nameFr: "Beni Bahdel", nameAr: "بني بهدل" },
    { nameFr: "Beni Snous", nameAr: "بني سنوس" },
    { nameFr: "Azail", nameAr: "العزايل" },
    { nameFr: "Djebala", nameAr: "جبالة" },
  ],
  '14': [
    { nameFr: "Mahdia", nameAr: "مهدية" },
    { nameFr: "Ain Dzarit", nameAr: "عين دزاريت" },
    { nameFr: "Sebaine", nameAr: "السبعين" },
    { nameFr: "Faidja", nameAr: "الفايجة" },
    { nameFr: "Si Abdelghani", nameAr: "سي عبد الغني" },
    { nameFr: "Sougueur", nameAr: "السوقر" },
    { nameFr: "Tousnina", nameAr: "توسنينة" },
    { nameFr: "Meghila", nameAr: "مغيلة" },
    { nameFr: "Sebt", nameAr: "السبت" },
    { nameFr: "Sidi Hosni", nameAr: "سيدي حسني" },
    { nameFr: "Ain El Hadid", nameAr: "عين الحديد" },
    { nameFr: "Frenda", nameAr: "فرندة" },
    { nameFr: "Takhemaret", nameAr: "تخمرت" },
    { nameFr: "Ain Kermes", nameAr: "عين كرمس" },
    { nameFr: "Djebilet Rosfa", nameAr: "جبيلات الرصفاء" },
    { nameFr: "Madna", nameAr: "مادنة" },
    { nameFr: "Medrissa", nameAr: "مدريسة" },
    { nameFr: "Sidi Abderrahmane", nameAr: "سيدي عبد الرحمن" },
    { nameFr: "Ksar Chellala", nameAr: "قصر الشلالة" },
    { nameFr: "Guertoufa", nameAr: "قرطوفة" },
    { nameFr: "Serghine", nameAr: "سرغين" },
    { nameFr: "Zmalet El Emir Abdelkade", nameAr: "زمالة  الأمير عبد القادر" },
    { nameFr: "Oued Lilli", nameAr: "وادي ليلي" },
    { nameFr: "Sidi Ali Mellal", nameAr: "سيدي علي ملال" },
    { nameFr: "Djillali Ben Amar", nameAr: "جيلالي بن عمار" },
    { nameFr: "Mechraa Safa", nameAr: "مشرع الصفا" },
    { nameFr: "Tagdempt", nameAr: "تاقدمت" },
    { nameFr: "Bougara", nameAr: "بوقرة" },
    { nameFr: "Hamadia", nameAr: "حمادية" },
    { nameFr: "Rechaiga", nameAr: "الرشايقة" },
    { nameFr: "Tidda", nameAr: "تيدة" },
    { nameFr: "Nadorah", nameAr: "الناظورة" },
    { nameFr: "Tiaret", nameAr: "تيارت" },
    { nameFr: "Medroussa", nameAr: "مدروسة" },
    { nameFr: "Mellakou", nameAr: "ملاكو" },
    { nameFr: "Sidi Bakhti", nameAr: "سيدي بختي" },
    { nameFr: "Ain Deheb", nameAr: "عين الذهب" },
    { nameFr: "Chehaima", nameAr: "شحيمة" },
    { nameFr: "Naima", nameAr: "النعيمة" },
    { nameFr: "Ain Bouchekif", nameAr: "عين بوشقيف" },
    { nameFr: "Dahmouni", nameAr: "دحموني" },
    { nameFr: "Rahouia", nameAr: "الرحوية" },
  ],
  '15': [
    { nameFr: "Mizrana", nameAr: "ميزرانـــة" },
    { nameFr: "Idjeur", nameAr: "إيجــار" },
    { nameFr: "Beni-Douala", nameAr: "بني دوالة" },
    { nameFr: "Beni-Zikki", nameAr: "بني زيكــي" },
    { nameFr: "Illoula Oumalou", nameAr: "إيلولة أومـــالو" },
    { nameFr: "Agouni-Gueghrane", nameAr: "أقني قغران" },
    { nameFr: "Ait Bouaddou", nameAr: "أيت بــوادو" },
    { nameFr: "Ouadhias", nameAr: "واضية" },
    { nameFr: "Tizi N'tleta", nameAr: "تيزي نثلاثة" },
    { nameFr: "Aghribs", nameAr: "أغريب" },
    { nameFr: "Ait-Chafaa", nameAr: "أيت شافع" },
    { nameFr: "Akerrou", nameAr: "أقرو" },
    { nameFr: "Azeffoun", nameAr: "أزفون" },
    { nameFr: "Iflissen", nameAr: "إفليـــسن" },
    { nameFr: "Tigzirt", nameAr: "تيقـزيرت" },
    { nameFr: "Assi-Youcef", nameAr: "أسي يوسف" },
    { nameFr: "Boghni", nameAr: "بوغني" },
    { nameFr: "Bounouh", nameAr: "بونوح" },
    { nameFr: "Mechtras", nameAr: "مشطراس" },
    { nameFr: "Draa-Ben-Khedda", nameAr: "ذراع بن خدة" },
    { nameFr: "Sidi Namane", nameAr: "سيدي نعمان" },
    { nameFr: "Tadmait", nameAr: "تادمايت" },
    { nameFr: "Tirmitine", nameAr: "تيرمتين" },
    { nameFr: "Ait Boumahdi", nameAr: "أيت بومهدي" },
    { nameFr: "Ait-Toudert", nameAr: "أيت تودرت" },
    { nameFr: "Beni-Aissi", nameAr: "بني عيسي" },
    { nameFr: "Ouacif", nameAr: "واسيف" },
    { nameFr: "Ait Khellili", nameAr: "أيت خليلي" },
    { nameFr: "Mekla", nameAr: "مقــلع" },
    { nameFr: "Souama", nameAr: "صوامـــع" },
    { nameFr: "Beni-Yenni", nameAr: "بني يني" },
    { nameFr: "Iboudrarene", nameAr: "إبودرارن" },
    { nameFr: "Tizi-Ouzou", nameAr: "تيزي وزو" },
    { nameFr: "Abi-Youcef", nameAr: "أبي يوسف" },
    { nameFr: "Ain-El-Hammam", nameAr: "عين الحمام" },
    { nameFr: "Ait-Yahia", nameAr: "أيت يحيى" },
    { nameFr: "Akbil", nameAr: "اقبيل" },
    { nameFr: "Boudjima", nameAr: "بوجيمة" },
    { nameFr: "Makouda", nameAr: "ماكودة" },
    { nameFr: "Ain-Zaouia", nameAr: "عين الزاوية" },
    { nameFr: "Ait Yahia Moussa", nameAr: "أيت يحي موسى" },
    { nameFr: "Draa-El-Mizan", nameAr: "ذراع الميزان" },
    { nameFr: "Frikat", nameAr: "فريقات" },
    { nameFr: "M'kira", nameAr: "مكيرة" },
    { nameFr: "Tizi-Gheniff", nameAr: "تيزي غنيف" },
    { nameFr: "Yatafene", nameAr: "يطــافن" },
    { nameFr: "Illilten", nameAr: "إيلـيــلتـن" },
    { nameFr: "Imsouhal", nameAr: "إمســوحال" },
    { nameFr: "Azazga", nameAr: "عزازقة" },
    { nameFr: "Freha", nameAr: "فريحة" },
    { nameFr: "Ifigha", nameAr: "إيفيغاء" },
    { nameFr: "Yakourene", nameAr: "إعــكورن" },
    { nameFr: "Zekri", nameAr: "زكري" },
    { nameFr: "Ait Aggouacha", nameAr: "أيت عقـواشة" },
    { nameFr: "Irdjen", nameAr: "إيرجـــن" },
    { nameFr: "Larbaa Nath Irathen", nameAr: "الأربعــاء ناث إيراثن" },
    { nameFr: "Ait-Oumalou", nameAr: "أيت  أومالو" },
    { nameFr: "Tizi-Rached", nameAr: "تيزي راشد" },
    { nameFr: "Ait-Aissa-Mimoun", nameAr: "أيت عيسى ميمون" },
    { nameFr: "Ouaguenoun", nameAr: "واقنون" },
    { nameFr: "Timizart", nameAr: "تيمـيزار" },
    { nameFr: "Maatkas", nameAr: "معـــاتقة" },
    { nameFr: "Souk-El-Tenine", nameAr: "سوق الإثنين" },
    { nameFr: "Ait-Mahmoud", nameAr: "أيت محمود" },
    { nameFr: "Beni Zmenzer", nameAr: "بنــــي زمنزار" },
    { nameFr: "Iferhounene", nameAr: "إفــرحــونان" },
    { nameFr: "Bouzeguene", nameAr: "بوزقــن" },
  ],
  '16': [
    { nameFr: "Hussein Dey", nameAr: "حسين داي" },
    { nameFr: "Les Eucalyptus", nameAr: "الكاليتوس" },
    { nameFr: "Sidi Moussa", nameAr: "سيدي موسى" },
    { nameFr: "Kouba", nameAr: "القبة" },
    { nameFr: "Mohamed Belouzdad", nameAr: "محمد بلوزداد" },
    { nameFr: "Ain Taya", nameAr: "عين طاية" },
    { nameFr: "Bab Ezzouar", nameAr: "باب الزوار" },
    { nameFr: "Bordj El Kiffan", nameAr: "برج الكيفان" },
    { nameFr: "Dar El Beida", nameAr: "الدار البيضاء" },
    { nameFr: "El Marsa", nameAr: "المرسى" },
    { nameFr: "Mohammadia", nameAr: "المحمدية" },
    { nameFr: "Bir Touta", nameAr: "بئر توتة" },
    { nameFr: "Ouled Chebel", nameAr: "اولاد شبل" },
    { nameFr: "Tessala El Merdja", nameAr: "تسالة المرجة" },
    { nameFr: "Herraoua", nameAr: "هراوة" },
    { nameFr: "Reghaia", nameAr: "رغاية" },
    { nameFr: "Rouiba", nameAr: "الرويبة" },
    { nameFr: "Maalma", nameAr: "المعالمة" },
    { nameFr: "Rahmania", nameAr: "الرحمانية" },
    { nameFr: "Souidania", nameAr: "سويدانية" },
    { nameFr: "Staoueli", nameAr: "سطاوالي" },
    { nameFr: "Zeralda", nameAr: "زرالدة" },
    { nameFr: "Baba Hassen", nameAr: "بابا حسن" },
    { nameFr: "Douira", nameAr: "الدويرة" },
    { nameFr: "Draria", nameAr: "الدرارية" },
    { nameFr: "El Achour", nameAr: "العاشور" },
    { nameFr: "Khraissia", nameAr: "الخرايسية" },
    { nameFr: "Ain Benian", nameAr: "عين بنيان" },
    { nameFr: "Cheraga", nameAr: "الشراقة" },
    { nameFr: "Dely Ibrahim", nameAr: "دالي ابراهيم" },
    { nameFr: "Hammamet", nameAr: "الحمامات" },
    { nameFr: "Ouled Fayet", nameAr: "اولاد فايت" },
    { nameFr: "Alger Centre", nameAr: "الجزائر الوسطى" },
    { nameFr: "El Madania", nameAr: "المدنية" },
    { nameFr: "El Mouradia", nameAr: "المرادية" },
    { nameFr: "Sidi M'hamed", nameAr: "سيدي امحمد" },
    { nameFr: "Sehaoula", nameAr: "السحاولة" },
    { nameFr: "Bologhine Ibnou Ziri", nameAr: "بولوغين بن زيري" },
    { nameFr: "Casbah", nameAr: "القصبة" },
    { nameFr: "Oued Koriche", nameAr: "وادي قريش" },
    { nameFr: "Rais Hamidou", nameAr: "الرايس حميدو" },
    { nameFr: "Bir Mourad Rais", nameAr: "بئر مراد رايس" },
    { nameFr: "Birkhadem", nameAr: "بئر خادم" },
    { nameFr: "Djasr Kasentina", nameAr: "جسر قسنطينة" },
    { nameFr: "Hydra", nameAr: "حيدرة" },
    { nameFr: "El Magharia", nameAr: "المغارية" },
    { nameFr: "Ben Aknoun", nameAr: "ابن عكنون" },
    { nameFr: "Beni Messous", nameAr: "بني مسوس" },
    { nameFr: "Bouzareah", nameAr: "بوزريعة" },
    { nameFr: "El Biar", nameAr: "الابيار" },
    { nameFr: "Bachedjerah", nameAr: "باش جراح" },
    { nameFr: "Bourouba", nameAr: "بوروبة" },
    { nameFr: "El Harrach", nameAr: "الحراش" },
    { nameFr: "Oued Smar", nameAr: "وادي السمار" },
    { nameFr: "Baraki", nameAr: "براقي" },
    { nameFr: "Bordj El Bahri", nameAr: "برج البحري" },
    { nameFr: "Bab El Oued", nameAr: "باب الوادي" },
  ],
  '17': [
    { nameFr: "Hassi El Euch", nameAr: "حاسي العش" },
    { nameFr: "Ain El Ibel", nameAr: "عين الإبل" },
    { nameFr: "El Guedid", nameAr: "القديد" },
    { nameFr: "Charef", nameAr: "الشارف" },
    { nameFr: "Benyagoub", nameAr: "بن يعقوب" },
    { nameFr: "Sidi Baizid", nameAr: "سيدي بايزيد" },
    { nameFr: "M'liliha", nameAr: "مليليحة" },
    { nameFr: "Dar Chioukh", nameAr: "دار الشيوخ" },
    { nameFr: "Taadmit", nameAr: "تعظميت" },
    { nameFr: "Had Sahary", nameAr: "حد الصحاري" },
    { nameFr: "Bouira Lahdab", nameAr: "بويرة الأحداب" },
    { nameFr: "Ain Fekka", nameAr: "عين فقه" },
    { nameFr: "Sidi Laadjel", nameAr: "سيدي لعجال" },
    { nameFr: "Hassi Fedoul", nameAr: "حاسي فدول" },
    { nameFr: "El Khemis", nameAr: "الخميس" },
    { nameFr: "Selmana", nameAr: "سلمانة" },
    { nameFr: "Sed Rahal", nameAr: "سد الرحال" },
    { nameFr: "Messaad", nameAr: "مسعد" },
    { nameFr: "Guettara", nameAr: "قطارة" },
    { nameFr: "Deldoul", nameAr: "دلدول" },
    { nameFr: "Zaccar", nameAr: "زكار" },
    { nameFr: "Douis", nameAr: "دويس" },
    { nameFr: "El Idrissia", nameAr: "الادريسية" },
    { nameFr: "Ain Chouhada", nameAr: "عين الشهداء" },
    { nameFr: "Djelfa", nameAr: "الجلفة" },
    { nameFr: "Birine", nameAr: "بيرين" },
    { nameFr: "Oum Laadham", nameAr: "أم العظام" },
    { nameFr: "Faidh El Botma", nameAr: "فيض البطمة" },
    { nameFr: "Amourah", nameAr: "عمورة" },
    { nameFr: "Zaafrane", nameAr: "زعفران" },
    { nameFr: "Guernini", nameAr: "قرنيني" },
    { nameFr: "Ain Oussera", nameAr: "عين وسارة" },
    { nameFr: "Benhar", nameAr: "بنهار" },
    { nameFr: "Ain Maabed", nameAr: "عين معبد" },
    { nameFr: "Hassi Bahbah", nameAr: "حاسي بحبح" },
    { nameFr: "Moudjebara", nameAr: "مجبارة" },
  ],
  '18': [
    { nameFr: "Jijel", nameAr: "جيجل" },
    { nameFr: "El Aouana", nameAr: "العوانة" },
    { nameFr: "Selma Benziada", nameAr: "سلمى بن زيادة" },
    { nameFr: "Erraguene Souissi", nameAr: "أراقن سويسي" },
    { nameFr: "Boussif Ouled Askeur", nameAr: "بوسيف أولاد عسكر" },
    { nameFr: "Ziama Mansouriah", nameAr: "زيامة منصورية" },
    { nameFr: "Chahna", nameAr: "الشحنة" },
    { nameFr: "Emir Abdelkader", nameAr: "الامير عبد القادر" },
    { nameFr: "Oudjana", nameAr: "وجانة" },
    { nameFr: "Taher", nameAr: "الطاهير" },
    { nameFr: "Chekfa", nameAr: "الشقفة" },
    { nameFr: "El Kennar Nouchfi", nameAr: "القنار نشفي" },
    { nameFr: "Sidi Abdelaziz", nameAr: "سيدي عبد العزيز" },
    { nameFr: "El Milia", nameAr: "الميلية" },
    { nameFr: "Ouled Yahia Khadrouch", nameAr: "أولاد يحيى خدروش" },
    { nameFr: "Ouled Rabah", nameAr: "أولاد رابح" },
    { nameFr: "Sidi Marouf", nameAr: "سيدي معروف" },
    { nameFr: "Ghebala", nameAr: "غبالة" },
    { nameFr: "Settara", nameAr: "السطارة" },
    { nameFr: "Bouraoui Belhadef", nameAr: "بوراوي بلهادف" },
    { nameFr: "El Ancer", nameAr: "العنصر" },
    { nameFr: "Khiri Oued Adjoul", nameAr: "خيري واد عجول" },
    { nameFr: "Djimla", nameAr: "جيملة" },
    { nameFr: "Kaous", nameAr: "قاوس" },
    { nameFr: "Texenna", nameAr: "تاكسنة" },
    { nameFr: "Bordj T'har", nameAr: "برج الطهر" },
    { nameFr: "Boudria Beniyadjis", nameAr: "بودريعة بني  ياجيس" },
    { nameFr: "Djemaa Beni Habibi", nameAr: "الجمعة بني حبيبي" },
  ],
  '19': [
    { nameFr: "Rosfa", nameAr: "الرصفة" },
    { nameFr: "Oued El Bared", nameAr: "واد البارد" },
    { nameFr: "Tizi N'bechar", nameAr: "تيزي نبشار" },
    { nameFr: "Mezloug", nameAr: "مزلوق" },
    { nameFr: "Guellal", nameAr: "قلال" },
    { nameFr: "Kasr El Abtal", nameAr: "قصر الابطال" },
    { nameFr: "Ouled Si Ahmed", nameAr: "أولاد سي أحمد" },
    { nameFr: "Ait Naoual Mezada", nameAr: "أيت نوال مزادة" },
    { nameFr: "Ait-Tizi", nameAr: "ايت تيزي" },
    { nameFr: "Bouandas", nameAr: "بوعنداس" },
    { nameFr: "Bousselam", nameAr: "بوسلام" },
    { nameFr: "Hamam Soukhna", nameAr: "حمام السخنة" },
    { nameFr: "Taya", nameAr: "الطاية" },
    { nameFr: "Tella", nameAr: "التلة" },
    { nameFr: "Ain Oulmene", nameAr: "عين ولمان" },
    { nameFr: "Boutaleb", nameAr: "بوطالب" },
    { nameFr: "Hamma", nameAr: "الحامة" },
    { nameFr: "Ouled Tebben", nameAr: "أولاد تبان" },
    { nameFr: "Amoucha", nameAr: "عموشة" },
    { nameFr: "Salah Bey", nameAr: "صالح باي" },
    { nameFr: "Ain Azel", nameAr: "عين أزال" },
    { nameFr: "Ain Lahdjar", nameAr: "عين الحجر" },
    { nameFr: "Beidha Bordj", nameAr: "بيضاء برج" },
    { nameFr: "Bir Haddada", nameAr: "بئر حدادة" },
    { nameFr: "Guenzet", nameAr: "قنزات" },
    { nameFr: "Harbil", nameAr: "حربيل" },
    { nameFr: "Ain-Roua", nameAr: "عين الروى" },
    { nameFr: "Beni Oussine", nameAr: "بني وسين" },
    { nameFr: "El Ouricia", nameAr: "أوريسيا" },
    { nameFr: "Bougaa", nameAr: "بوقاعة" },
    { nameFr: "Draa-Kebila", nameAr: "ذراع قبيلة" },
    { nameFr: "Hammam Guergour", nameAr: "حمام قرقور" },
    { nameFr: "Setif", nameAr: "سطيف" },
    { nameFr: "Ain El Kebira", nameAr: "عين الكبيرة" },
    { nameFr: "Dehamcha", nameAr: "الدهامشة" },
    { nameFr: "Ouled Addouane", nameAr: "أولاد عدوان" },
    { nameFr: "Ain-Sebt", nameAr: "عين السبت" },
    { nameFr: "Beni-Aziz", nameAr: "بني عزيز" },
    { nameFr: "Maaouia", nameAr: "معاوية" },
    { nameFr: "Bellaa", nameAr: "بلاعة" },
    { nameFr: "Bir-El-Arch", nameAr: "بئر العرش" },
    { nameFr: "El-Ouldja", nameAr: "الولجة" },
    { nameFr: "Tachouda", nameAr: "تاشودة" },
    { nameFr: "Tala-Ifacene", nameAr: "تالة إيفاسن" },
    { nameFr: "Serdj-El-Ghoul", nameAr: "سرج الغول" },
    { nameFr: "Guidjel", nameAr: "قجال" },
    { nameFr: "Ouled Sabor", nameAr: "أولاد صابر" },
    { nameFr: "Bazer-Sakra", nameAr: "بازر سكرة" },
    { nameFr: "El Eulma", nameAr: "العلمة" },
    { nameFr: "Guelta Zerka", nameAr: "قلتة زرقاء" },
    { nameFr: "Beni Fouda", nameAr: "بني فودة" },
    { nameFr: "Djemila", nameAr: "جميلة" },
    { nameFr: "Ain-Legradj", nameAr: "عين لقراج" },
    { nameFr: "Beni Chebana", nameAr: "بني شبانة" },
    { nameFr: "Beni Ourtilane", nameAr: "بني ورتيلان" },
    { nameFr: "Beni-Mouhli", nameAr: "بني موحلي" },
    { nameFr: "Ain Abessa", nameAr: "عين عباسة" },
    { nameFr: "Ain Arnat", nameAr: "عين أرنات" },
    { nameFr: "Babor", nameAr: "بابور" },
    { nameFr: "Maouaklane", nameAr: "ماوكلان" },
  ],
  '20': [
    { nameFr: "Saida", nameAr: "سعيدة" },
    { nameFr: "Tircine", nameAr: "تيرسين" },
    { nameFr: "Ouled Brahim", nameAr: "أولاد إبراهيم" },
    { nameFr: "Ain Soltane", nameAr: "عين السلطان" },
    { nameFr: "Maamora", nameAr: "المعمورة" },
    { nameFr: "El Hassasna", nameAr: "الحساسنة" },
    { nameFr: "Ain Sekhouna", nameAr: "عين السخونة" },
    { nameFr: "Sidi Boubekeur", nameAr: "سيدي بوبكر" },
    { nameFr: "Ouled Khaled", nameAr: "أولاد خالد" },
    { nameFr: "Hounet", nameAr: "هونت" },
    { nameFr: "Youb", nameAr: "يوب" },
    { nameFr: "Doui Thabet", nameAr: "دوي ثابت" },
    { nameFr: "Sidi Ahmed", nameAr: "سيدي احمد" },
    { nameFr: "Moulay Larbi", nameAr: "مولاي العربي" },
    { nameFr: "Ain El Hadjar", nameAr: "عين الحجر" },
    { nameFr: "Sidi Amar", nameAr: "سيدي عمر" },
  ],
  '21': [
    { nameFr: "Ain Bouziane", nameAr: "عين بوزيان" },
    { nameFr: "Salah Bouchaour", nameAr: "صالح بو الشعور" },
    { nameFr: "El Hadaiek", nameAr: "الحدائق" },
    { nameFr: "Zerdezas", nameAr: "زردازة" },
    { nameFr: "Ouled Habbaba", nameAr: "أولاد حبابة" },
    { nameFr: "Beni Oulbane", nameAr: "بني ولبان" },
    { nameFr: "Sidi Mezghiche", nameAr: "سيدي مزغيش" },
    { nameFr: "Beni Bechir", nameAr: "بني بشير" },
    { nameFr: "Ramdane Djamel", nameAr: "رمضان جمال" },
    { nameFr: "Bin El Ouiden", nameAr: "بين الويدان" },
    { nameFr: "Emjez Edchich", nameAr: "مجاز الدشيش" },
    { nameFr: "Tamalous", nameAr: "تمالوس" },
    { nameFr: "Ain Kechra", nameAr: "عين قشرة" },
    { nameFr: "Ouldja Boulbalout", nameAr: "الولجة بولبلوط" },
    { nameFr: "Oum Toub", nameAr: "أم الطوب" },
    { nameFr: "El Ghedir", nameAr: "الغدير" },
    { nameFr: "Kerkara", nameAr: "الكركرة" },
    { nameFr: "El Arrouch", nameAr: "الحروش" },
    { nameFr: "Zitouna", nameAr: "الزيتونة" },
    { nameFr: "Ouled Attia", nameAr: "أولاد عطية" },
    { nameFr: "Oued Zhour", nameAr: "وادي الزهور" },
    { nameFr: "Collo", nameAr: "القل" },
    { nameFr: "Cheraia", nameAr: "الشرايع" },
    { nameFr: "Beni Zid", nameAr: "بني زيد" },
    { nameFr: "Khenag Maoune", nameAr: "خناق مايو" },
    { nameFr: "El Marsa", nameAr: "المرسى" },
    { nameFr: "Ben Azzouz", nameAr: "بن عزوز" },
    { nameFr: "Bekkouche Lakhdar", nameAr: "بكوش لخضر" },
    { nameFr: "Es Sebt", nameAr: "السبت" },
    { nameFr: "Ain Charchar", nameAr: "عين شرشار" },
    { nameFr: "Azzaba", nameAr: "عزابة" },
    { nameFr: "Bouchetata", nameAr: "بوشطاطة" },
    { nameFr: "Filfila", nameAr: "فلفلة" },
    { nameFr: "Hammadi Krouma", nameAr: "حمادي كرومة" },
    { nameFr: "Skikda", nameAr: "سكيكدة" },
    { nameFr: "Ain Zouit", nameAr: "عين زويت" },
    { nameFr: "Djendel Saadi Mohamed", nameAr: "جندل سعدي محمد" },
    { nameFr: "Kanoua", nameAr: "قنواع" },
  ],
  '22': [
    { nameFr: "Sidi Ali Benyoub", nameAr: "سيدي علي بن يوب" },
    { nameFr: "Moulay Slissen", nameAr: "مولاي سليسن" },
    { nameFr: "El Hacaiba", nameAr: "الحصيبة" },
    { nameFr: "Ain Tindamine", nameAr: "عين تندمين" },
    { nameFr: "Tenira", nameAr: "تنيرة" },
    { nameFr: "Oued Sefioun", nameAr: "وادي سفيون" },
    { nameFr: "Hassi Dahou", nameAr: "حاسي دحو" },
    { nameFr: "Oued Taourira", nameAr: "وادي تاوريرة" },
    { nameFr: "Benachiba Chelia", nameAr: "بن عشيبة شلية" },
    { nameFr: "Sidi Yacoub", nameAr: "سيدي يعقوب" },
    { nameFr: "Sidi Lahcene", nameAr: "سيدي لحسن" },
    { nameFr: "Sidi Khaled", nameAr: "سيدي خالد" },
    { nameFr: "Tabia", nameAr: "طابية" },
    { nameFr: "Sidi Brahim", nameAr: "سيدي ابراهيم" },
    { nameFr: "Amarnas", nameAr: "العمارنة" },
    { nameFr: "Boukhanefis", nameAr: "بوخنفيس" },
    { nameFr: "Hassi Zahana", nameAr: "حاسي زهانة" },
    { nameFr: "Chetouane Belaila", nameAr: "شيطوان البلايلة" },
    { nameFr: "Ben Badis", nameAr: "بن باديس" },
    { nameFr: "Bedrabine El Mokrani", nameAr: "بضرابين المقراني" },
    { nameFr: "Sfisef", nameAr: "سفيزف" },
    { nameFr: "M'cid", nameAr: "مسيد" },
    { nameFr: "Boudjebaa El Bordj", nameAr: "بوجبهة البرج" },
    { nameFr: "Ain- Adden", nameAr: "عين أدن" },
    { nameFr: "Sidi Hamadouche", nameAr: "سيدي حمادوش" },
    { nameFr: "Sidi Chaib", nameAr: "سيدي شعيب" },
    { nameFr: "Makedra", nameAr: "مكدرة" },
    { nameFr: "Ain El Berd", nameAr: "عين البرد" },
    { nameFr: "Redjem Demouche", nameAr: "رجم دموش" },
    { nameFr: "Ras El Ma", nameAr: "راس الماء" },
    { nameFr: "Oued Sebaa", nameAr: "وادي السبع" },
    { nameFr: "Marhoum", nameAr: "مرحوم" },
    { nameFr: "Sidi Bel-Abbes", nameAr: "سيدي بلعباس" },
    { nameFr: "Ain Thrid", nameAr: "عين الثريد" },
    { nameFr: "Sehala Thaoura", nameAr: "السهالة الثورة" },
    { nameFr: "Tessala", nameAr: "تسالة" },
    { nameFr: "Belarbi", nameAr: "بلعربي" },
    { nameFr: "Mostefa  Ben Brahim", nameAr: "مصطفى بن ابراهيم" },
    { nameFr: "Tilmouni", nameAr: "تلموني" },
    { nameFr: "Zerouala", nameAr: "زروالة" },
    { nameFr: "Dhaya", nameAr: "الضاية" },
    { nameFr: "Mezaourou", nameAr: "مزاورو" },
    { nameFr: "Teghalimet", nameAr: "تغاليمت" },
    { nameFr: "Telagh", nameAr: "تلاغ" },
    { nameFr: "Ain Kada", nameAr: "عين قادة" },
    { nameFr: "Lamtar", nameAr: "لمطار" },
    { nameFr: "Sidi Ali Boussidi", nameAr: "سيدي علي بوسيدي" },
    { nameFr: "Sidi Dahou Zairs", nameAr: "سيدي دحو الزاير" },
    { nameFr: "Bir El Hammam", nameAr: "بئر الحمام" },
    { nameFr: "Merine", nameAr: "مرين" },
    { nameFr: "Tefessour", nameAr: "تفسور" },
    { nameFr: "Taoudmout", nameAr: "تاودموت" },
  ],
  '23': [
    { nameFr: "Annaba", nameAr: "عنابة" },
    { nameFr: "Seraidi", nameAr: "سرايدي" },
    { nameFr: "Berrahal", nameAr: "برحال" },
    { nameFr: "Oued El Aneb", nameAr: "واد العنب" },
    { nameFr: "El Hadjar", nameAr: "الحجار" },
    { nameFr: "Sidi Amar", nameAr: "سيدي عمار" },
    { nameFr: "El Bouni", nameAr: "البوني" },
    { nameFr: "Ain El Berda", nameAr: "عين الباردة" },
    { nameFr: "Cheurfa", nameAr: "الشرفة" },
    { nameFr: "El Eulma", nameAr: "العلمة" },
    { nameFr: "Treat", nameAr: "التريعات" },
    { nameFr: "Chetaibi", nameAr: "شطايبي" },
  ],
  '24': [
    { nameFr: "Nechmaya", nameAr: "نشماية" },
    { nameFr: "Bou Hamdane", nameAr: "بوحمدان" },
    { nameFr: "Hammam Debagh", nameAr: "حمام دباغ" },
    { nameFr: "Roknia", nameAr: "الركنية" },
    { nameFr: "Dahouara", nameAr: "الدهوارة" },
    { nameFr: "Hammam N'bail", nameAr: "حمام النبايل" },
    { nameFr: "Guelma", nameAr: "قالمة" },
    { nameFr: "Boumahra Ahmed", nameAr: "بومهرة أحمد" },
    { nameFr: "Ain Ben Beida", nameAr: "عين بن بيضاء" },
    { nameFr: "Bouchegouf", nameAr: "بوشقوف" },
    { nameFr: "Medjez Sfa", nameAr: "مجاز الصفاء" },
    { nameFr: "Oued Ferragha", nameAr: "وادي فراغة" },
    { nameFr: "Bouati Mahmoud", nameAr: "بوعاتي محمود" },
    { nameFr: "El Fedjoudj", nameAr: "الفجوج" },
    { nameFr: "Heliopolis", nameAr: "هيليوبوليس" },
    { nameFr: "Medjez Amar", nameAr: "مجاز عمار" },
    { nameFr: "Houari Boumedienne", nameAr: "هواري بومدين" },
    { nameFr: "Ras El Agba", nameAr: "رأس العقبة" },
    { nameFr: "Sellaoua Announa", nameAr: "سلاوة عنونة" },
    { nameFr: "Djeballah Khemissi", nameAr: "جبالة الخميسي" },
    { nameFr: "Bordj Sabath", nameAr: "برج صباط" },
    { nameFr: "Oued Zenati", nameAr: "وادي الزناتي" },
    { nameFr: "Ain Regada", nameAr: "عين رقادة" },
    { nameFr: "Ain Larbi", nameAr: "عين العربي" },
    { nameFr: "Ain Makhlouf", nameAr: "عين مخلوف" },
    { nameFr: "Tamlouka", nameAr: "تاملوكة" },
    { nameFr: "Ain Sandel", nameAr: "عين صندل" },
    { nameFr: "Bou Hachana", nameAr: "بوحشانة" },
    { nameFr: "Khezaras", nameAr: "لخزارة" },
    { nameFr: "Belkheir", nameAr: "بلخير" },
    { nameFr: "Beni Mezline", nameAr: "بني مزلين" },
    { nameFr: "Guelaat Bou Sbaa", nameAr: "قلعة بوصبع" },
    { nameFr: "Oued Cheham", nameAr: "وادي الشحم" },
    { nameFr: "Bendjarah", nameAr: "بن جراح" },
  ],
  '25': [
    { nameFr: "Didouche Mourad", nameAr: "ديدوش مراد" },
    { nameFr: "Hamma Bouziane", nameAr: "حامة بوزيان" },
    { nameFr: "Beni Hamidane", nameAr: "بني حميدان" },
    { nameFr: "Zighoud Youcef", nameAr: "زيغود يوسف" },
    { nameFr: "Ain Smara", nameAr: "عين السمارة" },
    { nameFr: "El Khroub", nameAr: "الخروب" },
    { nameFr: "Ouled Rahmoun", nameAr: "أولاد رحمون" },
    { nameFr: "Ain Abid", nameAr: "عين عبيد" },
    { nameFr: "Ben Badis", nameAr: "أبن باديس الهرية" },
    { nameFr: "Ibn Ziad", nameAr: "ابن زياد" },
    { nameFr: "Messaoud Boudjeriou", nameAr: "بوجريو مسعود" },
    { nameFr: "Constantine", nameAr: "قسنطينة" },
  ],
  '26': [
    { nameFr: "Ouled Hellal", nameAr: "أولاد هلال" },
    { nameFr: "Souagui", nameAr: "السواقي" },
    { nameFr: "Ksar El Boukhari", nameAr: "قصر البخاري" },
    { nameFr: "M'fatha", nameAr: "مفاتحة" },
    { nameFr: "Saneg", nameAr: "السانق" },
    { nameFr: "El Azizia", nameAr: "العزيزية" },
    { nameFr: "Maghraoua", nameAr: "مغراوة" },
    { nameFr: "Mihoub", nameAr: "ميهوب" },
    { nameFr: "Bouaiche", nameAr: "بوعيش" },
    { nameFr: "Boughzoul", nameAr: "بوغزول" },
    { nameFr: "Chabounia", nameAr: "الشهبونية" },
    { nameFr: "Hannacha", nameAr: "حناشة" },
    { nameFr: "Ouamri", nameAr: "عوامري" },
    { nameFr: "Oued Harbil", nameAr: "وادي حربيل" },
    { nameFr: "Beni Slimane", nameAr: "بني سليمان" },
    { nameFr: "Bouaichoune", nameAr: "بوعيشون" },
    { nameFr: "Ouled Bouachra", nameAr: "أولاد بوعشرة" },
    { nameFr: "Si Mahdjoub", nameAr: "سي المحجوب" },
    { nameFr: "Bouskene", nameAr: "بوسكن" },
    { nameFr: "Sidi Rabie", nameAr: "سيدي الربيع" },
    { nameFr: "Berrouaghia", nameAr: "البرواقية" },
    { nameFr: "Ouled Deid", nameAr: "أولاد دايد" },
    { nameFr: "Rebaia", nameAr: "الربعية" },
    { nameFr: "Medjebar", nameAr: "مجبر" },
    { nameFr: "Tletat Ed Douair", nameAr: "ثلاث دوائر" },
    { nameFr: "Zoubiria", nameAr: "الزبيرية" },
    { nameFr: "Aissaouia", nameAr: "العيساوية" },
    { nameFr: "El Haoudane", nameAr: "الحوضان" },
    { nameFr: "Mezerana", nameAr: "مزغنة" },
    { nameFr: "Tablat", nameAr: "تابلاط" },
    { nameFr: "Boghar", nameAr: "بوغار" },
    { nameFr: "Seghouane", nameAr: "سغوان" },
    { nameFr: "Draa Esmar", nameAr: "ذراع السمار" },
    { nameFr: "Medea", nameAr: "المدية" },
    { nameFr: "Tamesguida", nameAr: "تمسقيدة" },
    { nameFr: "Ben Chicao", nameAr: "بن شكاو" },
    { nameFr: "El Hamdania", nameAr: "الحمدانية" },
    { nameFr: "Ouzera", nameAr: "وزرة" },
    { nameFr: "Tizi Mahdi", nameAr: "تيزي مهدي" },
    { nameFr: "Ain Boucif", nameAr: "عين بوسيف" },
    { nameFr: "El Ouinet", nameAr: "العوينات" },
    { nameFr: "Kef Lakhdar", nameAr: "الكاف الاخضر" },
    { nameFr: "Ouled Emaaraf", nameAr: "أولاد امعرف" },
    { nameFr: "Sidi Demed", nameAr: "سيدي دامد" },
    { nameFr: "Baata", nameAr: "بعطة" },
    { nameFr: "El Omaria", nameAr: "العمارية" },
    { nameFr: "Ouled Brahim", nameAr: "أولاد إبراهيم" },
    { nameFr: "Bir Ben Laabed", nameAr: "بئر بن عابد" },
    { nameFr: "El Guelbelkebir", nameAr: "القلب الكبير" },
    { nameFr: "Sedraya", nameAr: "سدراية" },
    { nameFr: "Ain Ouksir", nameAr: "عين اقصير" },
    { nameFr: "Chelalet El Adhaoura", nameAr: "شلالة العذاورة" },
    { nameFr: "Cheniguel", nameAr: "شنيقل" },
    { nameFr: "Tafraout", nameAr: "تفراوت" },
    { nameFr: "Bouchrahil", nameAr: "بوشراحيل" },
    { nameFr: "Khams Djouamaa", nameAr: "خمس جوامع" },
    { nameFr: "Sidi Naamane", nameAr: "سيدي نعمان" },
    { nameFr: "Aziz", nameAr: "عزيز" },
    { nameFr: "Derrag", nameAr: "دراق" },
    { nameFr: "Oum El Djellil", nameAr: "أم الجليل" },
    { nameFr: "Djouab", nameAr: "جواب" },
    { nameFr: "Sidi Zahar", nameAr: "سيدي زهار" },
    { nameFr: "Sidi Ziane", nameAr: "سيدي زيان" },
    { nameFr: "Ouled Antar", nameAr: "أولاد عنتر" },
  ],
  '27': [
    { nameFr: "Fornaka", nameAr: "فرناقة" },
    { nameFr: "Oued El Kheir", nameAr: "وادي الخير" },
    { nameFr: "Hassiane", nameAr: "الحسيان (بني ياحي" },
    { nameFr: "Hassi Mameche", nameAr: "حاسي ماماش" },
    { nameFr: "Mazagran", nameAr: "مزغران" },
    { nameFr: "Stidia", nameAr: "ستيدية" },
    { nameFr: "Ain-Tedles", nameAr: "عين تادلس" },
    { nameFr: "Sidi Belaattar", nameAr: "سيدي بلعطار" },
    { nameFr: "Sour", nameAr: "سور" },
    { nameFr: "Ain-Boudinar", nameAr: "عين بودينار" },
    { nameFr: "Kheir-Eddine", nameAr: "خير الدين" },
    { nameFr: "Sayada", nameAr: "صيادة" },
    { nameFr: "Sidi Ali", nameAr: "سيدي علي" },
    { nameFr: "Tazgait", nameAr: "تزقايت" },
    { nameFr: "Benabdelmalek Ramdane", nameAr: "بن عبد المالك رمضان" },
    { nameFr: "Mostaganem", nameAr: "مستغانم" },
    { nameFr: "Hadjadj", nameAr: "حجاج" },
    { nameFr: "Sidi-Lakhdar", nameAr: "سيدي لخضر" },
    { nameFr: "Achaacha", nameAr: "عشعاشة" },
    { nameFr: "Khadra", nameAr: "خضرة" },
    { nameFr: "Nekmaria", nameAr: "نكمارية" },
    { nameFr: "Ouled Boughalem", nameAr: "أولاد بوغالم" },
    { nameFr: "Bouguirat", nameAr: "بوقيراط" },
    { nameFr: "Safsaf", nameAr: "صفصاف" },
    { nameFr: "Sirat", nameAr: "سيرات" },
    { nameFr: "Souaflia", nameAr: "السوافلية" },
    { nameFr: "Ain-Sidi Cherif", nameAr: "عين سيدي الشريف" },
    { nameFr: "Mansourah", nameAr: "منصورة" },
    { nameFr: "Mesra", nameAr: "ماسرة" },
    { nameFr: "Touahria", nameAr: "الطواهرية" },
    { nameFr: "Ain-Nouissy", nameAr: "عين نويسي" },
    { nameFr: "Ouled-Maalah", nameAr: "أولاد مع الله" },
  ],
  '28': [
    { nameFr: "Chellal", nameAr: "شلال" },
    { nameFr: "Ouled Madhi", nameAr: "أولاد ماضي" },
    { nameFr: "Khettouti Sed-El-Jir", nameAr: "خطوطي سد الجير" },
    { nameFr: "Belaiba", nameAr: "بلعايبة" },
    { nameFr: "Berhoum", nameAr: "برهوم" },
    { nameFr: "Dehahna", nameAr: "دهاهنة" },
    { nameFr: "Magra", nameAr: "مقرة" },
    { nameFr: "Beni Ilmane", nameAr: "بني يلمان" },
    { nameFr: "Bouti Sayeh", nameAr: "بوطي السايح" },
    { nameFr: "Sidi Aissa", nameAr: "سيدي عيسى" },
    { nameFr: "Ain El Hadjel", nameAr: "عين الحجل" },
    { nameFr: "Sidi Hadjeres", nameAr: "سيدي هجرس" },
    { nameFr: "Bou Saada", nameAr: "بوسعادة" },
    { nameFr: "El Hamel", nameAr: "الهامل" },
    { nameFr: "Oulteme", nameAr: "ولتام" },
    { nameFr: "Benzouh", nameAr: "بن زوه" },
    { nameFr: "Ouled Sidi Brahim", nameAr: "أولاد سيدي ابراهيم" },
    { nameFr: "Sidi Ameur", nameAr: "سيدي عامر" },
    { nameFr: "Tamsa", nameAr: "تامسة" },
    { nameFr: "Ben Srour", nameAr: "بن سرور" },
    { nameFr: "Mohamed Boudiaf", nameAr: "محمد بوضياف" },
    { nameFr: "Ouled Slimane", nameAr: "أولاد سليمان" },
    { nameFr: "Zarzour", nameAr: "زرزور" },
    { nameFr: "Ain El Melh", nameAr: "عين الملح" },
    { nameFr: "Ain Fares", nameAr: "عين فارس" },
    { nameFr: "Ain Rich", nameAr: "عين الريش" },
    { nameFr: "Bir Foda", nameAr: "بئر فضة" },
    { nameFr: "Sidi M'hamed", nameAr: "سيدي امحمد" },
    { nameFr: "Medjedel", nameAr: "امجدل" },
    { nameFr: "Menaa", nameAr: "مناعة" },
    { nameFr: "Djebel Messaad", nameAr: "جبل مساعد" },
    { nameFr: "Slim", nameAr: "سليم" },
    { nameFr: "M'sila", nameAr: "المسيلة" },
    { nameFr: "Hammam Dalaa", nameAr: "حمام الضلعة" },
    { nameFr: "Ouanougha", nameAr: "ونوغة" },
    { nameFr: "Ouled Mansour", nameAr: "أولاد منصور" },
    { nameFr: "Tarmount", nameAr: "تارمونت" },
    { nameFr: "Maadid", nameAr: "المعاضيد" },
    { nameFr: "M'tarfa", nameAr: "المطارفة" },
    { nameFr: "Maarif", nameAr: "معاريف" },
    { nameFr: "Ouled Derradj", nameAr: "أولاد دراج" },
    { nameFr: "Souamaa", nameAr: "السوامع" },
    { nameFr: "El Houamed", nameAr: "الحوامد" },
    { nameFr: "Khoubana", nameAr: "خبانة" },
    { nameFr: "M'cif", nameAr: "مسيف" },
    { nameFr: "Ain Khadra", nameAr: "عين الخضراء" },
    { nameFr: "Ouled Addi Guebala", nameAr: "أولاد عدي لقبالة" },
  ],
  '29': [
    { nameFr: "Oued El Abtal", nameAr: "وادي الأبطال" },
    { nameFr: "Sidi Abdelmoumene", nameAr: "سيدي عبد المومن" },
    { nameFr: "Sedjerara", nameAr: "سجرارة" },
    { nameFr: "Mohammadia", nameAr: "المحمدية" },
    { nameFr: "Tighennif", nameAr: "تيغنيف" },
    { nameFr: "Mocta-Douz", nameAr: "مقطع الدوز" },
    { nameFr: "Ferraguig", nameAr: "فراقيق" },
    { nameFr: "El Ghomri", nameAr: "الغمري" },
    { nameFr: "Zahana", nameAr: "زهانة" },
    { nameFr: "El Gaada", nameAr: "القعدة" },
    { nameFr: "Ras El Ain Amirouche", nameAr: "رأس عين عميروش" },
    { nameFr: "Oggaz", nameAr: "عقاز" },
    { nameFr: "Alaimia", nameAr: "العلايمية" },
    { nameFr: "Sig", nameAr: "سيق" },
    { nameFr: "Chorfa", nameAr: "الشرفاء" },
    { nameFr: "Bou Henni", nameAr: "بوهني" },
    { nameFr: "El Mamounia", nameAr: "المأمونية" },
    { nameFr: "El Gueitena", nameAr: "القطنة" },
    { nameFr: "Ain Fares", nameAr: "عين فارس" },
    { nameFr: "Gharrous", nameAr: "غروس" },
    { nameFr: "Benian", nameAr: "بنيان" },
    { nameFr: "Aouf", nameAr: "عوف" },
    { nameFr: "Guerdjoum", nameAr: "قرجوم" },
    { nameFr: "Ain Frass", nameAr: "عين أفرص" },
    { nameFr: "Ain Fekan", nameAr: "عين فكان" },
    { nameFr: "Khalouia", nameAr: "خلوية" },
    { nameFr: "El Menaouer", nameAr: "المنور" },
    { nameFr: "El Bordj", nameAr: "البرج" },
    { nameFr: "Sidi Boussaid", nameAr: "سيدي بوسعيد" },
    { nameFr: "Matemore", nameAr: "المطمور" },
    { nameFr: "Sidi Kada", nameAr: "سيدي قادة" },
    { nameFr: "Makhda", nameAr: "ماقضة" },
    { nameFr: "Mascara", nameAr: "معسكر" },
    { nameFr: "Bouhanifia", nameAr: "بوحنيفية" },
    { nameFr: "Ghriss", nameAr: "غريس" },
    { nameFr: "Hacine", nameAr: "حسين" },
    { nameFr: "El Keurt", nameAr: "القرط" },
    { nameFr: "Froha", nameAr: "فروحة" },
    { nameFr: "Tizi", nameAr: "تيزي" },
    { nameFr: "Sehailia", nameAr: "السهايلية" },
    { nameFr: "Maoussa", nameAr: "ماوسة" },
    { nameFr: "Sidi Abdeldjebar", nameAr: "سيدي عبد الجبار" },
    { nameFr: "El Hachem", nameAr: "الحشم" },
    { nameFr: "Nesmot", nameAr: "نسمط" },
    { nameFr: "Zelamta", nameAr: "زلامطة" },
    { nameFr: "Ain Ferah", nameAr: "عين فراح" },
    { nameFr: "Oued Taria", nameAr: "وادي التاغية" },
  ],
  '30': [
    { nameFr: "Ouargla", nameAr: "ورقلة" },
    { nameFr: "Hassi Messaoud", nameAr: "حاسي مسعود" },
    { nameFr: "Ain Beida", nameAr: "عين البيضاء" },
    { nameFr: "Hassi Ben Abdellah", nameAr: "حاسي بن عبد الله" },
    { nameFr: "Sidi Khouiled", nameAr: "سيدي خويلد" },
    { nameFr: "El Borma", nameAr: "البرمة" },
    { nameFr: "Rouissat", nameAr: "الرويسات" },
    { nameFr: "N'goussa", nameAr: "انقوسة" },
  ],
  '31': [
    { nameFr: "Sidi Chami", nameAr: "سيدي الشحمي" },
    { nameFr: "Hassi Mefsoukh", nameAr: "حاسي مفسوخ" },
    { nameFr: "Bir El Djir", nameAr: "بئر الجير" },
    { nameFr: "Hassi Ben Okba", nameAr: "حاسي بن عقبة" },
    { nameFr: "Gdyel", nameAr: "قديل" },
    { nameFr: "Hassi Bounif", nameAr: "حاسي بونيف" },
    { nameFr: "El Kerma", nameAr: "الكرمة" },
    { nameFr: "Es Senia", nameAr: "السانية" },
    { nameFr: "Ben Freha", nameAr: "بن فريحة" },
    { nameFr: "Arzew", nameAr: "أرزيو" },
    { nameFr: "Sidi Ben Yebka", nameAr: "سيدي بن يبقى" },
    { nameFr: "Ain Biya", nameAr: "عين البية" },
    { nameFr: "Bethioua", nameAr: "بطيوة" },
    { nameFr: "Marsat El Hadjadj", nameAr: "مرسى الحجاج" },
    { nameFr: "Ain Turk", nameAr: "عين الترك" },
    { nameFr: "Oran", nameAr: "وهران" },
    { nameFr: "El Ancor", nameAr: "العنصر" },
    { nameFr: "Mers El Kebir", nameAr: "المرسى الكبير" },
    { nameFr: "Boufatis", nameAr: "بوفاتيس" },
    { nameFr: "El Braya", nameAr: "البراية" },
    { nameFr: "Oued Tlelat", nameAr: "وادي تليلات" },
    { nameFr: "Ain Kerma", nameAr: "عين الكرمة" },
    { nameFr: "Boutlelis", nameAr: "بوتليليس" },
    { nameFr: "Messerghin", nameAr: "مسرغين" },
    { nameFr: "Bousfer", nameAr: "بوسفر" },
    { nameFr: "Tafraoui", nameAr: "طفراوي" },
  ],
  '32': [
    { nameFr: "Ain El Orak", nameAr: "عين العراك" },
    { nameFr: "Krakda", nameAr: "كراكدة" },
    { nameFr: "Sidi Slimane", nameAr: "سيدي سليمان" },
    { nameFr: "Sidi Ameur", nameAr: "سيدي عامر" },
    { nameFr: "Boualem", nameAr: "بوعلام" },
    { nameFr: "El Bnoud", nameAr: "البنود" },
    { nameFr: "Bougtoub", nameAr: "بوقطب" },
    { nameFr: "El Kheiter", nameAr: "الخيثر" },
    { nameFr: "Tousmouline", nameAr: "توسمولين" },
    { nameFr: "Sidi Tiffour", nameAr: "سيدي طيفور" },
    { nameFr: "Stitten", nameAr: "ستيتن" },
    { nameFr: "El Bayadh", nameAr: "البيض" },
    { nameFr: "Rogassa", nameAr: "رقاصة" },
    { nameFr: "El Mehara", nameAr: "المحرة" },
    { nameFr: "Kef El Ahmar", nameAr: "الكاف الأحمر" },
    { nameFr: "Brezina", nameAr: "بريزينة" },
    { nameFr: "Ghassoul", nameAr: "الغاسول" },
    { nameFr: "Labiodh Sidi Cheikh", nameAr: "الأبيض سيدي الشيخ" },
    { nameFr: "Boussemghoun", nameAr: "بوسمغون" },
    { nameFr: "Cheguig", nameAr: "الشقيق" },
    { nameFr: "Chellala", nameAr: "شلالة" },
    { nameFr: "Arbaouat", nameAr: "اربوات" },
  ],
  '33': [
    { nameFr: "Bordj Omar Driss", nameAr: "برج عمر إدريس" },
    { nameFr: "Debdeb", nameAr: "دبداب" },
    { nameFr: "In Amenas", nameAr: "إن أمناس" },
    { nameFr: "Illizi", nameAr: "إيليزي" },
  ],
  '34': [
    { nameFr: "Elhammadia", nameAr: "الحمادية" },
    { nameFr: "Ouled Sidi-Brahim", nameAr: "أولاد سيدي ابراهيم" },
    { nameFr: "Ain Taghrout", nameAr: "عين تاغروت" },
    { nameFr: "Tixter", nameAr: "تيكستار" },
    { nameFr: "Belimour", nameAr: "بليمور" },
    { nameFr: "El Annasseur", nameAr: "العناصر" },
    { nameFr: "Ghailasa", nameAr: "غيلاسة" },
    { nameFr: "Taglait", nameAr: "تقلعيت" },
    { nameFr: "Bordj Ghedir", nameAr: "برج الغدير" },
    { nameFr: "El Euch", nameAr: "العش" },
    { nameFr: "Sidi-Embarek", nameAr: "سيدي أمبارك" },
    { nameFr: "Khelil", nameAr: "خليل" },
    { nameFr: "Bir Kasdali", nameAr: "بئر قاصد علي" },
    { nameFr: "Tefreg", nameAr: "تفرق" },
    { nameFr: "El Main", nameAr: "الماين" },
    { nameFr: "Djaafra", nameAr: "جعافرة" },
    { nameFr: "Colla", nameAr: "القلة" },
    { nameFr: "Teniet En Nasr", nameAr: "ثنية النصر" },
    { nameFr: "El M'hir", nameAr: "المهير" },
    { nameFr: "Ksour", nameAr: "القصور" },
    { nameFr: "Mansoura", nameAr: "المنصورة" },
    { nameFr: "Haraza", nameAr: "حرازة" },
    { nameFr: "Rabta", nameAr: "الرابطة" },
    { nameFr: "El Achir", nameAr: "الياشير" },
    { nameFr: "Hasnaoua", nameAr: "حسناوة" },
    { nameFr: "Medjana", nameAr: "مجانة" },
    { nameFr: "Ain Tesra", nameAr: "عين تسرة" },
    { nameFr: "Ouled Brahem", nameAr: "أولاد أبراهم" },
    { nameFr: "Ras El Oued", nameAr: "رأس الوادي" },
    { nameFr: "Bordj Zemmoura", nameAr: "برج زمورة" },
    { nameFr: "Ouled Dahmane", nameAr: "أولاد دحمان" },
    { nameFr: "Tassamert", nameAr: "تسامرت" },
    { nameFr: "B. B. Arreridj", nameAr: "برج بوعريرج" },
    { nameFr: "Ben Daoud", nameAr: "بن داود" },
  ],
  '35': [
    { nameFr: "El Kharrouba", nameAr: "الخروبة" },
    { nameFr: "Dellys", nameAr: "دلس" },
    { nameFr: "Ben Choud", nameAr: "بن شود" },
    { nameFr: "Afir", nameAr: "أعفير" },
    { nameFr: "Thenia", nameAr: "الثنية" },
    { nameFr: "Beni Amrane", nameAr: "بني عمران" },
    { nameFr: "Khemis El Khechna", nameAr: "خميس الخشنة" },
    { nameFr: "Ammal", nameAr: "عمال" },
    { nameFr: "Timezrit", nameAr: "تيمزريت" },
    { nameFr: "Zemmouri", nameAr: "زموري" },
    { nameFr: "Larbatache", nameAr: "الاربعطاش" },
    { nameFr: "Isser", nameAr: "يسر" },
    { nameFr: "Chabet El Ameur", nameAr: "شعبة العامر" },
    { nameFr: "Ouled Aissa", nameAr: "أولاد عيسى" },
    { nameFr: "Naciria", nameAr: "الناصرية" },
    { nameFr: "Bouzegza Keddara", nameAr: "بوزقزة قدارة" },
    { nameFr: "Souk El Had", nameAr: "سوق الحد" },
    { nameFr: "Sidi Daoud", nameAr: "سيدي داود" },
    { nameFr: "Baghlia", nameAr: "بغلية" },
    { nameFr: "Leghata", nameAr: "لقاطة" },
    { nameFr: "Djinet", nameAr: "جنات" },
    { nameFr: "Tidjelabine", nameAr: "تيجلابين" },
    { nameFr: "Si Mustapha", nameAr: "سي مصطفى" },
    { nameFr: "Ouled Hedadj", nameAr: "أولاد هداج" },
    { nameFr: "Ouled Moussa", nameAr: "أولاد موسى" },
    { nameFr: "Boumerdes", nameAr: "بومرداس" },
    { nameFr: "Corso", nameAr: "قورصو" },
    { nameFr: "Bordj Menaiel", nameAr: "برج منايل" },
    { nameFr: "Boudouaou", nameAr: "بودواو" },
    { nameFr: "Boudouaou El Bahri", nameAr: "بودواو البحري" },
    { nameFr: "Taourga", nameAr: "تاورقة" },
    { nameFr: "Hammedi", nameAr: "حمادي" },
  ],
  '36': [
    { nameFr: "Ain El Assel", nameAr: "عين العسل" },
    { nameFr: "Bougous", nameAr: "بوقوس" },
    { nameFr: "El Tarf", nameAr: "الطارف" },
    { nameFr: "Zitouna", nameAr: "الزيتونة" },
    { nameFr: "Besbes", nameAr: "البسباس" },
    { nameFr: "Ain Kerma", nameAr: "عين الكرمة" },
    { nameFr: "Bouhadjar", nameAr: "بوحجار" },
    { nameFr: "Hammam Beni Salah", nameAr: "حمام بني صالح" },
    { nameFr: "Oued Zitoun", nameAr: "وادي الزيتون" },
    { nameFr: "Ben M Hidi", nameAr: "بن مهيدي" },
    { nameFr: "Berrihane", nameAr: "بريحان" },
    { nameFr: "Chebaita Mokhtar", nameAr: "شبيطة مختار" },
    { nameFr: "Echatt", nameAr: "الشط" },
    { nameFr: "El Aioun", nameAr: "العيون" },
    { nameFr: "El Kala", nameAr: "القالة" },
    { nameFr: "Souarekh", nameAr: "السوارخ" },
    { nameFr: "Zerizer", nameAr: "زريزر" },
    { nameFr: "Bouteldja", nameAr: "بوثلجة" },
    { nameFr: "Chefia", nameAr: "الشافية" },
    { nameFr: "Lac Des Oiseaux", nameAr: "بحيرة الطيور" },
    { nameFr: "Chihani", nameAr: "شحاني" },
    { nameFr: "Raml Souk", nameAr: "رمل السوق" },
    { nameFr: "Asfour", nameAr: "عصفور" },
    { nameFr: "Drean", nameAr: "الذرعـان" },
  ],
  '37': [
    { nameFr: "Tindouf", nameAr: "تندوف" },
    { nameFr: "Oum El Assel", nameAr: "أم العسل" },
  ],
  '38': [
    { nameFr: "Khemisti", nameAr: "خميستي" },
    { nameFr: "Theniet El Had", nameAr: "ثنية الاحد" },
    { nameFr: "Ouled Bessam", nameAr: "أولاد بسام" },
    { nameFr: "Sidi Boutouchent", nameAr: "سيدي بوتوشنت" },
    { nameFr: "Tissemsilt", nameAr: "تيسمسيلت" },
    { nameFr: "Sidi Lantri", nameAr: "سيدي العنتري" },
    { nameFr: "Beni Chaib", nameAr: "بني شعيب" },
    { nameFr: "Beni Lahcene", nameAr: "بني لحسن" },
    { nameFr: "Sidi Abed", nameAr: "سيدي عابد" },
    { nameFr: "Sidi Slimane", nameAr: "سيدي سليمان" },
    { nameFr: "Boucaid", nameAr: "بوقائد" },
    { nameFr: "Larbaa", nameAr: "الأربعاء" },
    { nameFr: "Lazharia", nameAr: "الأزهرية" },
    { nameFr: "Lardjem", nameAr: "لرجام" },
    { nameFr: "Melaab", nameAr: "الملعب" },
    { nameFr: "Layoune", nameAr: "العيون" },
    { nameFr: "Tamellahet", nameAr: "تملاحت" },
    { nameFr: "Youssoufia", nameAr: "اليوسفية" },
    { nameFr: "Bordj El Emir Abdelkader", nameAr: "برج الأمير عبد القادر" },
    { nameFr: "Ammari", nameAr: "عماري" },
    { nameFr: "Maacem", nameAr: "المعاصم" },
    { nameFr: "Bordj Bounaama", nameAr: "برج بونعامة" },
  ],
  '39': [
    { nameFr: "Douar El Maa", nameAr: "دوار الماء" },
    { nameFr: "El Ogla", nameAr: "العقلة" },
    { nameFr: "Magrane", nameAr: "المقرن" },
    { nameFr: "Sidi Aoun", nameAr: "سيدي عون" },
    { nameFr: "Mih Ouansa", nameAr: "اميه وانسة" },
    { nameFr: "Kouinine", nameAr: "كوينين" },
    { nameFr: "Bayadha", nameAr: "البياضة" },
    { nameFr: "Nakhla", nameAr: "النخلة" },
    { nameFr: "Robbah", nameAr: "الرباح" },
    { nameFr: "Guemar", nameAr: "قمار" },
    { nameFr: "Ben Guecha", nameAr: "بن  قشة" },
    { nameFr: "Ourmes", nameAr: "ورماس" },
    { nameFr: "Taghzout", nameAr: "تغزوت" },
    { nameFr: "Hamraia", nameAr: "الحمراية" },
    { nameFr: "Reguiba", nameAr: "الرقيبة" },
    { nameFr: "Debila", nameAr: "الدبيلة" },
    { nameFr: "Hassani Abdelkrim", nameAr: "حساني عبد الكريم" },
    { nameFr: "Hassi Khalifa", nameAr: "حاسي خليفة" },
    { nameFr: "Trifaoui", nameAr: "الطريفاوي" },
    { nameFr: "Taleb Larbi", nameAr: "الطالب العربي" },
    { nameFr: "Oued El Alenda", nameAr: "وادي العلندة" },
    { nameFr: "El-Oued", nameAr: "الوادي" },
  ],
  '40': [
    { nameFr: "Khirane", nameAr: "خيران" },
    { nameFr: "Babar", nameAr: "بابار" },
    { nameFr: "El Mahmal", nameAr: "المحمل" },
    { nameFr: "Ouled Rechache", nameAr: "أولاد رشاش" },
    { nameFr: "Djellal", nameAr: "جلال" },
    { nameFr: "Yabous", nameAr: "يابوس" },
    { nameFr: "Khenchela", nameAr: "خنشلة" },
    { nameFr: "Kais", nameAr: "قايس" },
    { nameFr: "Chelia", nameAr: "شلية" },
    { nameFr: "Remila", nameAr: "الرميلة" },
    { nameFr: "Taouzianat", nameAr: "تاوزيانت" },
    { nameFr: "Baghai", nameAr: "بغاي" },
    { nameFr: "El Hamma", nameAr: "الحامة" },
    { nameFr: "Ensigha", nameAr: "انسيغة" },
    { nameFr: "Tamza", nameAr: "طامزة" },
    { nameFr: "Ain Touila", nameAr: "عين الطويلة" },
    { nameFr: "M'toussa", nameAr: "متوسة" },
    { nameFr: "Bouhmama", nameAr: "بوحمامة" },
    { nameFr: "El Oueldja", nameAr: "الولجة" },
    { nameFr: "M'sara", nameAr: "مصارة" },
    { nameFr: "Chechar", nameAr: "ششار" },
  ],
  '41': [
    { nameFr: "Souk Ahras", nameAr: "سوق أهراس" },
    { nameFr: "Ain Soltane", nameAr: "عين سلطان" },
    { nameFr: "Sedrata", nameAr: "سدراتة" },
    { nameFr: "Hanencha", nameAr: "الحنانشة" },
    { nameFr: "Machroha", nameAr: "المشروحة" },
    { nameFr: "Ain Zana", nameAr: "عين الزانة" },
    { nameFr: "Ouled Driss", nameAr: "أولاد إدريس" },
    { nameFr: "Terraguelt", nameAr: "ترقالت" },
    { nameFr: "Oum El Adhaim", nameAr: "أم العظايم" },
    { nameFr: "Oued Kebrit", nameAr: "وادي الكبريت" },
    { nameFr: "Tiffech", nameAr: "تيفاش" },
    { nameFr: "Ragouba", nameAr: "الراقوبة" },
    { nameFr: "Drea", nameAr: "الدريعة" },
    { nameFr: "Taoura", nameAr: "تاورة" },
    { nameFr: "Zaarouria", nameAr: "الزعرورية" },
    { nameFr: "Haddada", nameAr: "الحدادة" },
    { nameFr: "Khedara", nameAr: "الخضارة" },
    { nameFr: "Ouled Moumen", nameAr: "أولاد مومن" },
    { nameFr: "Merahna", nameAr: "المراهنة" },
    { nameFr: "Ouillen", nameAr: "ويلان" },
    { nameFr: "Sidi Fredj", nameAr: "سيدي فرج" },
    { nameFr: "Bir Bouhouche", nameAr: "بئر بوحوش" },
    { nameFr: "Safel El Ouiden", nameAr: "سافل الويدان" },
    { nameFr: "Khemissa", nameAr: "خميسة" },
    { nameFr: "M'daourouche", nameAr: "مداوروش" },
    { nameFr: "Zouabi", nameAr: "الزوابي" },
  ],
  '42': [
    { nameFr: "Hadjout", nameAr: "حجوط" },
    { nameFr: "Merad", nameAr: "مراد" },
    { nameFr: "Menaceur", nameAr: "مناصر" },
    { nameFr: "Aghbal", nameAr: "أغبال" },
    { nameFr: "Nador", nameAr: "الناظور" },
    { nameFr: "Sidi-Amar", nameAr: "سيدي عامر" },
    { nameFr: "Gouraya", nameAr: "قوراية" },
    { nameFr: "Messelmoun", nameAr: "مسلمون" },
    { nameFr: "Cherchell", nameAr: "شرشال" },
    { nameFr: "Hadjret Ennous", nameAr: "حجرة النص" },
    { nameFr: "Sidi Ghiles", nameAr: "سيدي غيلاس" },
    { nameFr: "Damous", nameAr: "الداموس" },
    { nameFr: "Larhat", nameAr: "الأرهاط" },
    { nameFr: "Fouka", nameAr: "فوكة" },
    { nameFr: "Ain Tagourait", nameAr: "عين تاقورايت" },
    { nameFr: "Bou Haroun", nameAr: "بوهارون" },
    { nameFr: "Bou Ismail", nameAr: "بواسماعيل" },
    { nameFr: "Khemisti", nameAr: "خميستي" },
    { nameFr: "Ahmer El Ain", nameAr: "أحمر العين" },
    { nameFr: "Bourkika", nameAr: "بورقيقة" },
    { nameFr: "Douaouda", nameAr: "دواودة" },
    { nameFr: "Sidi Rached", nameAr: "سيدي راشد" },
    { nameFr: "Attatba", nameAr: "الحطاطبة" },
    { nameFr: "Chaiba", nameAr: "الشعيبة" },
    { nameFr: "Kolea", nameAr: "القليعة" },
    { nameFr: "Sidi Semiane", nameAr: "سيدي سميان" },
    { nameFr: "Tipaza", nameAr: "تيبازة" },
    { nameFr: "Beni Mileuk", nameAr: "بني ميلك" },
  ],
  '43': [
    { nameFr: "El Mechira", nameAr: "مشيرة" },
    { nameFr: "El Ayadi Barbes", nameAr: "العياضي برباس" },
    { nameFr: "Ain Beida Harriche", nameAr: " عين البيضاء أحريش" },
    { nameFr: "Tassala Lematai", nameAr: "تسالة لمطاعي" },
    { nameFr: "Terrai Bainen", nameAr: "ترعي باينان" },
    { nameFr: "Amira Arres", nameAr: "اعميرة اراس" },
    { nameFr: "Tassadane Haddada", nameAr: "تسدان حدادة" },
    { nameFr: "Minar Zarza", nameAr: "مينار زارزة" },
    { nameFr: "Sidi Merouane", nameAr: "سيدي مروان" },
    { nameFr: "Chigara", nameAr: "الشيقارة" },
    { nameFr: "Hamala", nameAr: "حمالة" },
    { nameFr: "Grarem Gouga", nameAr: "القرارم قوقة" },
    { nameFr: "Tiberguent", nameAr: "تيبرقنت" },
    { nameFr: "Rouached", nameAr: "الرواشد" },
    { nameFr: "Derrahi Bousselah", nameAr: "دراحي بوصلاح" },
    { nameFr: "Zeghaia", nameAr: "زغاية" },
    { nameFr: "Oued Endja", nameAr: "وادي النجاء" },
    { nameFr: "Ahmed Rachedi", nameAr: "أحمد راشدي" },
    { nameFr: "Tadjenanet", nameAr: "تاجنانت" },
    { nameFr: "Ain Mellouk", nameAr: "عين الملوك" },
    { nameFr: "Ouled Khalouf", nameAr: "أولاد اخلوف" },
    { nameFr: "Benyahia Abderrahmane", nameAr: "بن يحي عبد الرحمن" },
    { nameFr: "Teleghma", nameAr: "التلاغمة" },
    { nameFr: "Oued Seguen", nameAr: "وادي سقان" },
    { nameFr: "Oued Athmenia", nameAr: "وادي العثمانية" },
    { nameFr: "Ain Tine", nameAr: "عين التين" },
    { nameFr: "Chelghoum Laid", nameAr: "شلغوم العيد" },
    { nameFr: "Yahia Beniguecha", nameAr: "يحي بني قشة" },
    { nameFr: "Ferdjioua", nameAr: "فرجيوة" },
    { nameFr: "Sidi Khelifa", nameAr: "سيدي خليفة" },
    { nameFr: "Mila", nameAr: "ميلة" },
    { nameFr: "Bouhatem", nameAr: "بوحاتم" },
  ],
  '44': [
    { nameFr: "Khemis-Miliana", nameAr: "خميس مليانة" },
    { nameFr: "Sidi-Lakhdar", nameAr: "سيدي الأخضر" },
    { nameFr: "Ain-Benian", nameAr: "عين البنيان" },
    { nameFr: "Ain-Torki", nameAr: "عين التركي" },
    { nameFr: "Hammam-Righa", nameAr: "حمام ريغة" },
    { nameFr: "Bourached", nameAr: "بوراشد" },
    { nameFr: "Hoceinia", nameAr: "الحسينية" },
    { nameFr: "Djelida", nameAr: "جليدة" },
    { nameFr: "Arib", nameAr: "عريب" },
    { nameFr: "Djemaa Ouled Cheikh", nameAr: "جمعة أولاد الشيخ" },
    { nameFr: "El-Amra", nameAr: "العامرة" },
    { nameFr: "El-Attaf", nameAr: "العطاف" },
    { nameFr: "Tiberkanine", nameAr: "تبركانين" },
    { nameFr: "Ain-Bouyahia", nameAr: "عين بويحيى" },
    { nameFr: "El-Abadia", nameAr: "العبادية" },
    { nameFr: "Tacheta Zegagha", nameAr: "تاشتة زقاغة" },
    { nameFr: "Birbouche", nameAr: "بربوش" },
    { nameFr: "Djendel", nameAr: "جندل" },
    { nameFr: "Ben Allal", nameAr: "بن علال" },
    { nameFr: "Oued Chorfa", nameAr: "وادي الشرفاء" },
    { nameFr: "Boumedfaa", nameAr: "بومدفع" },
    { nameFr: "Ain-Lechiakh", nameAr: "عين الاشياخ" },
    { nameFr: "Ain-Soltane", nameAr: "عين السلطان" },
    { nameFr: "Oued Djemaa", nameAr: "واد الجمعة" },
    { nameFr: "El-Maine", nameAr: "الماين" },
    { nameFr: "Rouina", nameAr: "الروينة" },
    { nameFr: "Zeddine", nameAr: "زدين" },
    { nameFr: "Bir-Ould-Khelifa", nameAr: "بئر ولد خليفة" },
    { nameFr: "Bordj-Emir-Khaled", nameAr: "برج الأمير خالد" },
    { nameFr: "Tarik-Ibn-Ziad", nameAr: "طارق بن زياد" },
    { nameFr: "Bathia", nameAr: "بطحية" },
    { nameFr: "Belaas", nameAr: "بلعاص" },
    { nameFr: "Hassania", nameAr: "الحسانية" },
    { nameFr: "Ain-Defla", nameAr: "عين الدفلى" },
    { nameFr: "Miliana", nameAr: "مليانة" },
    { nameFr: "Mekhatria", nameAr: "المخاطرية" },
  ],
  '45': [
    { nameFr: "Tiout", nameAr: "تيوت" },
    { nameFr: "Moghrar", nameAr: "مغرار" },
    { nameFr: "Asla", nameAr: "عسلة" },
    { nameFr: "Kasdir", nameAr: "القصدير" },
    { nameFr: "Makmen Ben Amar", nameAr: "مكمن بن عمار" },
    { nameFr: "Ain Sefra", nameAr: "عين الصفراء" },
    { nameFr: "Mecheria", nameAr: "المشرية" },
    { nameFr: "El Biodh", nameAr: "البيوض" },
    { nameFr: "Ain Ben Khelil", nameAr: "عين بن خليل" },
    { nameFr: "Naama", nameAr: "النعامة" },
    { nameFr: "Djenienne Bourezg", nameAr: "جنين بورزق" },
    { nameFr: "Sfissifa", nameAr: "سفيسيفة" },
  ],
  '46': [
    { nameFr: "Sidi Boumediene", nameAr: "سيدي بومدين" },
    { nameFr: "Tamzoura", nameAr: "تامزورة" },
    { nameFr: "Chaabat El Ham", nameAr: "شعبة اللحم" },
    { nameFr: "El Maleh", nameAr: "المالح" },
    { nameFr: "Ouled Kihal", nameAr: "أولاد الكيحل" },
    { nameFr: "Chentouf", nameAr: "شنتوف" },
    { nameFr: "Terga", nameAr: "تارقة" },
    { nameFr: "Oued Sebbah", nameAr: "وادي الصباح" },
    { nameFr: "El Amria", nameAr: "العامرية" },
    { nameFr: "Hassi El Ghella", nameAr: "حاسي الغلة" },
    { nameFr: "Ouled Boudjemaa", nameAr: "أولاد بوجمعة" },
    { nameFr: "Aghlal", nameAr: "أغلال" },
    { nameFr: "Ain Kihal", nameAr: "عين الكيحل" },
    { nameFr: "Ain Tolba", nameAr: "عين الطلبة" },
    { nameFr: "Aoubellil", nameAr: "عقب الليل" },
    { nameFr: "Beni Saf", nameAr: "بني صاف" },
    { nameFr: "Hassasna", nameAr: "الحساسنة" },
    { nameFr: "Emir Abdelkader", nameAr: "الأمير عبد القادر" },
    { nameFr: "Sidi Safi", nameAr: "سيدي صافي" },
    { nameFr: "Oulhaca El Gheraba", nameAr: "ولهاصة الغرابة" },
    { nameFr: "Sidi Ouriache", nameAr: "سيدي ورياش" },
    { nameFr: "Ain El Arbaa", nameAr: "عين الأربعاء" },
    { nameFr: "El Messaid", nameAr: "المساعيد" },
    { nameFr: "Oued Berkeche", nameAr: "وادي برقش" },
    { nameFr: "Sidi Ben Adda", nameAr: "سيدي بن عدة" },
    { nameFr: "Ain Temouchent", nameAr: "عين تموشنت" },
    { nameFr: "Bouzedjar", nameAr: "بوزجار" },
    { nameFr: "Hammam Bou Hadjar", nameAr: "حمام بوحجر" },
  ],
  '47': [
    { nameFr: "Dhayet Bendhahoua", nameAr: "ضاية بن ضحوة" },
    { nameFr: "Mansoura", nameAr: "المنصورة" },
    { nameFr: "El Atteuf", nameAr: "العطف" },
    { nameFr: "Bounoura", nameAr: "بونورة" },
    { nameFr: "Zelfana", nameAr: "زلفانة" },
    { nameFr: "El Guerrara", nameAr: "القرارة" },
    { nameFr: "Sebseb", nameAr: "سبسب" },
    { nameFr: "Metlili", nameAr: "متليلي" },
    { nameFr: "Berriane", nameAr: "بريان" },
    { nameFr: "Ghardaia", nameAr: "غرداية" },
  ],
  '48': [
    { nameFr: "El-Guettar", nameAr: "القطار" },
    { nameFr: "Ouled Aiche", nameAr: "أولاد يعيش" },
    { nameFr: "Beni Dergoun", nameAr: "بني درقن" },
    { nameFr: "Dar Ben Abdelah", nameAr: "دار بن عبد الله" },
    { nameFr: "Zemmoura", nameAr: "زمورة" },
    { nameFr: "Djidiouia", nameAr: "جديوية" },
    { nameFr: "Hamri", nameAr: "حمري" },
    { nameFr: "Belaassel Bouzagza", nameAr: "بلعسل بوزقزة" },
    { nameFr: "El-Matmar", nameAr: "المطمر" },
    { nameFr: "Sidi Khettab", nameAr: "سيدي  خطاب" },
    { nameFr: "Sidi M'hamed Benaouda", nameAr: "سيدي امحمد بن عودة" },
    { nameFr: "Ain-Tarek", nameAr: "عين طارق" },
    { nameFr: "Had Echkalla", nameAr: "حد الشكالة" },
    { nameFr: "El Ouldja", nameAr: "الولجة" },
    { nameFr: "Mazouna", nameAr: "مازونة" },
    { nameFr: "Ain Rahma", nameAr: "عين الرحمة" },
    { nameFr: "Kalaa", nameAr: "القلعة" },
    { nameFr: "Sidi Saada", nameAr: "سيدي سعادة" },
    { nameFr: "Yellel", nameAr: "يلل" },
    { nameFr: "Souk El Had", nameAr: "سوق الحد" },
    { nameFr: "Mendes", nameAr: "منداس" },
    { nameFr: "Oued Essalem", nameAr: "وادي السلام" },
    { nameFr: "Sidi Lazreg", nameAr: "سيدي لزرق" },
    { nameFr: "Ammi Moussa", nameAr: "عمي موسى" },
    { nameFr: "Ouarizane", nameAr: "واريزان" },
    { nameFr: "Merdja Sidi Abed", nameAr: "مرجة سيدي عابد" },
    { nameFr: "Ouled Sidi Mihoub", nameAr: "أولاد سيدي الميهوب" },
    { nameFr: "Bendaoud", nameAr: "بن داود" },
    { nameFr: "Oued-Rhiou", nameAr: "وادي رهيو" },
    { nameFr: "El Hassi", nameAr: "الحاسي" },
    { nameFr: "Sidi M'hamed Benali", nameAr: "سيدي أمحمد بن علي" },
    { nameFr: "Mediouna", nameAr: "مديونة" },
    { nameFr: "Beni Zentis", nameAr: "بني زنطيس" },
    { nameFr: "Oued El Djemaa", nameAr: "وادي الجمعة" },
    { nameFr: "Lahlef", nameAr: "لحلاف" },
    { nameFr: "Relizane", nameAr: "غليزان" },
    { nameFr: "El H'madna", nameAr: "الحمادنة" },
    { nameFr: "Ramka", nameAr: "الرمكة" },
  ],
  '49': [
    { nameFr: "Tinerkouk", nameAr: "تنركوك" },
    { nameFr: "Timimoun", nameAr: "تيميمون" },
    { nameFr: "Ouled Said", nameAr: "أولاد السعيد" },
    { nameFr: "Metarfa", nameAr: "المطارفة" },
    { nameFr: "Talmine", nameAr: "طالمين" },
    { nameFr: "Ouled Aissa", nameAr: "أولاد عيسى" },
    { nameFr: "Charouine", nameAr: "شروين" },
    { nameFr: "Aougrout", nameAr: "أوقروت" },
    { nameFr: "Deldoul", nameAr: "دلدول" },
    { nameFr: "Ksar Kaddour", nameAr: "قصر قدور" },
  ],
  '50': [
    { nameFr: "Timiaouine", nameAr: "تيمياوين" },
    { nameFr: "Bordj Badji Mokhtar", nameAr: "برج باجي مختار" },
  ],
  '51': [
    { nameFr: "Ras El Miad", nameAr: "رأس الميعاد" },
    { nameFr: "Besbes", nameAr: "بسباس" },
    { nameFr: "Sidi Khaled", nameAr: "سيدي  خالد" },
    { nameFr: "Doucen", nameAr: "الدوسن" },
    { nameFr: "Chaiba", nameAr: "الشعيبة" },
    { nameFr: "Ouled Djellal", nameAr: "أولاد جلال" },
  ],
  '52': [
    { nameFr: "Beni-Abbes", nameAr: "بني عباس" },
    { nameFr: "Tamtert", nameAr: "تامترت" },
    { nameFr: "Igli", nameAr: "إقلي" },
    { nameFr: "El Ouata", nameAr: "الواتة" },
    { nameFr: "Ouled-Khodeir", nameAr: "أولاد خضير" },
    { nameFr: "Kerzaz", nameAr: "كرزاز" },
    { nameFr: "Timoudi", nameAr: "تيمودي" },
    { nameFr: "Ksabi", nameAr: "القصابي" },
    { nameFr: "Beni-Ikhlef", nameAr: "بن يخلف" },
  ],
  '53': [
    { nameFr: "Inghar", nameAr: "إينغر" },
    { nameFr: "Ain Salah", nameAr: "عين صالح" },
    { nameFr: "Foggaret Ezzoua", nameAr: "فقارة الزوى" },
  ],
  '54': [
    { nameFr: "Tin Zouatine", nameAr: "تين زواتين" },
    { nameFr: "Ain Guezzam", nameAr: "عين قزام" },
  ],
  '55': [
    { nameFr: "Temacine", nameAr: "تماسين" },
    { nameFr: "Sidi Slimane", nameAr: "سيدي سليمان" },
    { nameFr: "Megarine", nameAr: "المقارين" },
    { nameFr: "Nezla", nameAr: "النزلة" },
    { nameFr: "Blidet Amor", nameAr: "بلدة اعمر" },
    { nameFr: "Tebesbest", nameAr: "تبسبست" },
    { nameFr: "Touggourt", nameAr: "تقرت" },
    { nameFr: "Taibet", nameAr: "الطيبات" },
    { nameFr: "El Alia", nameAr: "العالية" },
    { nameFr: "El-Hadjira", nameAr: "الحجيرة" },
    { nameFr: "Benaceur", nameAr: "بن ناصر" },
    { nameFr: "M'naguer", nameAr: "المنقر" },
    { nameFr: "Zaouia El Abidia", nameAr: "الزاوية العابدية" },
  ],
  '56': [
    { nameFr: "Djanet", nameAr: "جانت" },
    { nameFr: "Bordj El Haouass", nameAr: "برج الحواس" },
  ],
  '57': [
    { nameFr: "Oum Touyour", nameAr: "أم الطيور" },
    { nameFr: "Sidi Amrane", nameAr: "سيدي عمران" },
    { nameFr: "M'rara", nameAr: "المرارة" },
    { nameFr: "Djamaa", nameAr: "جامعة" },
    { nameFr: "Tenedla", nameAr: "تندلة" },
    { nameFr: "El-M'ghaier", nameAr: "المغير" },
    { nameFr: "Still", nameAr: "سطيل" },
    { nameFr: "Sidi Khelil", nameAr: "سيدي خليل" },
  ],
  '58': [
    { nameFr: "El Meniaa", nameAr: "المنيعة" },
    { nameFr: "Hassi Gara", nameAr: "حاسي القارة" },
    { nameFr: "Hassi Fehal", nameAr: "حاسي الفحل" },
  ],
}

const WILAYA_PRICES: Record<string, { home: number; office: number }> = {
  '01': { home: 1100, office: 750 }, '02': { home: 680, office: 400 },
  '03': { home: 800, office: 500 }, '04': { home: 680, office: 400 },
  '05': { home: 700, office: 400 }, '06': { home: 700, office: 400 },
  '07': { home: 800, office: 500 }, '08': { home: 1000, office: 700 },
  '09': { home: 500, office: 350 }, '10': { home: 600, office: 400 },
  '11': { home: 1500, office: 1050 }, '12': { home: 720, office: 450 },
  '13': { home: 700, office: 400 }, '14': { home: 700, office: 400 },
  '15': { home: 600, office: 400 }, '16': { home: 400, office: 300 },
  '17': { home: 800, office: 500 }, '18': { home: 700, office: 400 },
  '19': { home: 680, office: 400 }, '20': { home: 730, office: 450 },
  '21': { home: 700, office: 400 }, '22': { home: 700, office: 400 },
  '23': { home: 700, office: 450 }, '24': { home: 700, office: 400 },
  '25': { home: 680, office: 400 }, '26': { home: 600, office: 400 },
  '27': { home: 700, office: 400 }, '28': { home: 700, office: 400 },
  '29': { home: 700, office: 400 }, '30': { home: 900, office: 550 },
  '31': { home: 580, office: 400 }, '32': { home: 970, office: 700 },
  '33': { home: 1500, office: 1050 }, '34': { home: 680, office: 400 },
  '35': { home: 530, office: 350 }, '36': { home: 730, office: 450 },
  '37': { home: 1100, office: 750 }, '38': { home: 700, office: 400 },
  '39': { home: 900, office: 550 }, '40': { home: 700, office: 400 },
  '41': { home: 730, office: 450 }, '42': { home: 530, office: 350 },
  '43': { home: 700, office: 400 }, '44': { home: 700, office: 400 },
  '45': { home: 930, office: 550 }, '46': { home: 700, office: 400 },
  '47': { home: 850, office: 500 }, '48': { home: 700, office: 400 },
  '49': { home: 1100, office: 750 }, '50': { home: 1200, office: 800 },
  '51': { home: 800, office: 500 }, '52': { home: 1000, office: 750 },
  '53': { home: 1400, office: 950 }, '54': { home: 1800, office: 1200 },
  '55': { home: 930, office: 550 }, '56': { home: 2100, office: 1500 },
  '57': { home: 930, office: 550 }, '58': { home: 850, office: 500 },
}

export function getCommunesByWilaya(wilayaCode: string): Commune[] {
  return COMMUNES[wilayaCode] || [{ nameFr: 'Chef-lieu de wilaya', nameAr: 'مقر دائرة' }]
}

export function getDeliveryPrice(code: string, type: 'domicile' | 'bureau'): number {
  const p = WILAYA_PRICES[code]
  return p ? p[type === 'domicile' ? 'home' : 'office'] : 400
}
