export interface Wilaya {
  code: string
  nameFr: string
  nameAr: string
}

export const WILAYAS: Wilaya[] = [
  { code: '01', nameFr: 'Adrar', nameAr: 'أدرار' },
  { code: '02', nameFr: 'Chlef', nameAr: 'الشلف' },
  { code: '03', nameFr: 'Laghouat', nameAr: 'الأغواط' },
  { code: '04', nameFr: 'Oum El Bouaghi', nameAr: 'أم البواقي' },
  { code: '05', nameFr: 'Batna', nameAr: 'باتنة' },
  { code: '06', nameFr: 'Béjaïa', nameAr: 'بجاية' },
  { code: '07', nameFr: 'Biskra', nameAr: 'بسكرة' },
  { code: '08', nameFr: 'Béchar', nameAr: 'بشار' },
  { code: '09', nameFr: 'Blida', nameAr: 'البليدة' },
  { code: '10', nameFr: 'Bouira', nameAr: 'البويرة' },
  { code: '11', nameFr: 'Tamanrasset', nameAr: 'تمنراست' },
  { code: '12', nameFr: 'Tébessa', nameAr: 'تبسة' },
  { code: '13', nameFr: 'Tlemcen', nameAr: 'تلمسان' },
  { code: '14', nameFr: 'Tiaret', nameAr: 'تيارت' },
  { code: '15', nameFr: 'Tizi Ouzou', nameAr: 'تيزي وزو' },
  { code: '16', nameFr: 'Alger', nameAr: 'الجزائر' },
  { code: '17', nameFr: 'Djelfa', nameAr: 'الجلفة' },
  { code: '18', nameFr: 'Jijel', nameAr: 'جيجل' },
  { code: '19', nameFr: 'Sétif', nameAr: 'سطيف' },
  { code: '20', nameFr: 'Saïda', nameAr: 'سعيدة' },
  { code: '21', nameFr: 'Skikda', nameAr: 'سكيكدة' },
  { code: '22', nameFr: 'Sidi Bel Abbès', nameAr: 'سيدي بلعباس' },
  { code: '23', nameFr: 'Annaba', nameAr: 'عنابة' },
  { code: '24', nameFr: 'Guelma', nameAr: 'قالمة' },
  { code: '25', nameFr: 'Constantine', nameAr: 'قسنطينة' },
  { code: '26', nameFr: 'Médéa', nameAr: 'المدية' },
  { code: '27', nameFr: 'Mostaganem', nameAr: 'مستغانم' },
  { code: '28', nameFr: "M'Sila", nameAr: 'المسيلة' },
  { code: '29', nameFr: 'Mascara', nameAr: 'معسكر' },
  { code: '30', nameFr: 'Ouargla', nameAr: 'ورقلة' },
  { code: '31', nameFr: 'Oran', nameAr: 'وهران' },
  { code: '32', nameFr: 'El Bayadh', nameAr: 'البيض' },
  { code: '33', nameFr: 'Illizi', nameAr: 'إليزي' },
  { code: '34', nameFr: 'Bordj Bou Arréridj', nameAr: 'برج بوعريريج' },
  { code: '35', nameFr: 'Boumerdès', nameAr: 'بومرداس' },
  { code: '36', nameFr: 'El Tarf', nameAr: 'الطارف' },
  { code: '37', nameFr: 'Tindouf', nameAr: 'تندوف' },
  { code: '38', nameFr: 'Tissemsilt', nameAr: 'تيسمسيلت' },
  { code: '39', nameFr: 'El Oued', nameAr: 'الوادي' },
  { code: '40', nameFr: 'Khenchela', nameAr: 'خنشلة' },
  { code: '41', nameFr: 'Souk Ahras', nameAr: 'سوق أهراس' },
  { code: '42', nameFr: 'Tipaza', nameAr: 'تيبازة' },
  { code: '43', nameFr: 'Mila', nameAr: 'ميلة' },
  { code: '44', nameFr: 'Aïn Defla', nameAr: 'عين الدفلى' },
  { code: '45', nameFr: 'Naâma', nameAr: 'النعامة' },
  { code: '46', nameFr: 'Aïn Témouchent', nameAr: 'عين تيموشنت' },
  { code: '47', nameFr: 'Ghardaïa', nameAr: 'غرداية' },
  { code: '48', nameFr: 'Relizane', nameAr: 'غليزان' },
  { code: '49', nameFr: 'Timimoun', nameAr: 'تيميمون' },
  { code: '50', nameFr: 'Bordj Badji Mokhtar', nameAr: 'برج باجي مختار' },
  { code: '51', nameFr: 'Ouled Djellal', nameAr: 'أولاد جلال' },
  { code: '52', nameFr: 'Béni Abbès', nameAr: 'بني عباس' },
  { code: '53', nameFr: 'In Salah', nameAr: 'عين صالح' },
  { code: '54', nameFr: 'In Guezzam', nameAr: 'عين قزام' },
  { code: '55', nameFr: 'Touggourt', nameAr: 'تقرت' },
  { code: '56', nameFr: 'Djanet', nameAr: 'جانت' },
  { code: '57', nameFr: "El M'Ghair", nameAr: 'المغير' },
  { code: '58', nameFr: 'El Meniaa', nameAr: 'المنيعة' },
]

export const COMMUNES: Record<string, string[]> = {
  '01': ['Adrar','Aoulef','Timimoun','Reggane','Tsabit','Fenoughil','Zaouiet Kounta','Bouda','Aougrout','Talmine','Akabli'],
  '02': ['Chlef','Ténès','Abou El Hassan','Béni Haoua','Oued Fodda','Taougrite','Bénairia','El Karimia','Zeboudja','Harchoun','Ouled Fares'],
  '03': ['Laghouat','Aflou','Hassi Rmel','Ksar El Hirane','El Assafia','Brida','Gueltat Sidi Saad','Ain Madhi','Tadjmout','Sidi Makhlouf'],
  '04': ['Oum El Bouaghi','Ain Beida','Ain Mlila','Ain Fakroun','Meskiana','Souk Naamane','Ouled Hamla','Ain Zitoun','Fkirina','Sigus'],
  '05': ['Batna','Arris','Barika','Ain Touta','Tazoult','Merouana','Djezzar','Seriana','Ichmoul','Foum Toub','N\'Gaous','Timgad','El Madher'],
  '06': ['Béjaïa','Akbou','El Kseur','Amizour','Sidi Aich','Kherrata','Tazmalt','Aokas','Bejaia','Tichy','Souk El Tenine','Tifelfel','Ouzellaguen'],
  '07': ['Biskra','Tolga','Sidi Okba','El Kantara','Zeribet El Oued','Ain Naga','Djemorah','Lichana','Ouled Djellal','Ras El Miad','Foughala'],
  '08': ['Béchar','Abadla','Beni Abbes','Kenadsa','Lahmar','Taghit','Erg Ferradj','Igli','Kerzaz','Ouled Khodeir'],
  '09': ['Blida','Boufarik','Larbaa','Meftah','Ouled Yaïch','Bougara','Chiffa','Bouinan','Oued Alleug','Soumaa','Ben Khellil','Guerrouaou','Ain Romana'],
  '10': ['Bouira','Lakhdaria','M\'Chedallah','Ain Bessem','Ain El Hadjar','Sour El Ghozlane','El Asnam','Haizer','Kadiria','Bechloul','Chorfa'],
  '11': ['Tamanrasset','In Salah','In Ghar','In Amguel','Tazrouk','Abalessa','Foggaret Ezzaouia'],
  '12': ['Tébessa','Bir El Ater','El Kouif','Cheria','El Ogla','Hammamet','Ouenza','Morsott','Negrine','El Aouinet','Bir Dhehb'],
  '13': ['Tlemcen','Maghnia','Ghazaouet','Nedroma','Bab El Assa','Remchi','Ain Tallout','Sidi Djillali','Mansourah','Sebdou','Hennaya','Chetouane'],
  '14': ['Tiaret','Frenda','Ksar Chellala','Mahdia','Ain Deheb','Sidi Ali Melal','Oued Lili','Mechraa Safa','Zmalet El Emir','Rahouia','Melaab'],
  '15': ['Tizi Ouzou','Ain El Hammam','Azazga','Draa Ben Khedda','Boghni','Tigzirt','Larbaa Nath Irathen','Ouacifs','Makouda','Beni Douala','Iferhounene'],
  '16': ['Alger Centre','Bab El Oued','Bab Ezzouar','Bir Mourad Raïs','Bir Touta','Birkhadem','Bordj El Bahri','Bordj El Kiffan','Chéraga','Dar El Beïda','Draria','El Biar','El Harrach','Hussein Dey','Hydra','Kouba','Les Eucalyptus','Mahelma','Mohammadia','Oued Smar','Ouled Fayet','Reghaia','Rouiba','Saoula','Souidania','Staouali','Tessala El Merdja','Tipaza','Zeralda'],
  '17': ['Djelfa','Ain Oussera','Messaad','Hassi Bahbah','Birine','El Idrissia','Charef','Faidh El Botma','Dar Chioukh','Zaccar'],
  '18': ['Jijel','El Milia','Ziama Mansouriah','Taher','Chekfa','El Aouana','Settara','Ghebala','Texenna','Bouchegouf'],
  '19': ['Sétif','El Eulma','Ain El Kebira','Ain Azel','Bougaa','Ain Oulmane','Guenzet','Amoucha','El Ouricia','Ain Arnat','Maoklane'],
  '20': ['Saïda','Ain El Hadjar','Sidi Amar','Youb','Sidi Boubekeur','El Hassasna','Ain Sultan','Ouled Brahim'],
  '21': ['Skikda','Azzaba','Collo','El Harrouch','Ben Azzouz','Tamalous','Ain Charchar','Oum Toub','Zitouna'],
  '22': ['Sidi Bel Abbès','Telagh','Ain Trid','Ben Badis','Mostefa Ben Brahim','Sidi Brahim','Ras El Ma','Redjem Demouche','Tessala','Sidi Lahcene'],
  '23': ['Annaba','El Bouni','El Hadjar','Ain El Berda','Berrahal','Chetaïbi','Seraïdi','Treat'],
  '24': ['Guelma','Bouchegouf','Heliopolis','Ain Makhlouf','Ain Sandel','Ain Ben Beida','El Fedjoudj','Oued Zenati'],
  '25': ['Constantine','El Khroub','Ain Abid','Hamma Bouziane','Ibn Ziad','Didouche Mourad','Zighoud Youcef','Ain Smara'],
  '26': ['Médéa','Berrouaghia','Tablat','Ksar El Boukhari','Boughezoul','Ain Boucif','El Aissaouia','Ouamri','Chelalet El Adhaoura','Aziz'],
  '27': ['Mostaganem','Ain Tadles','Stidia','Mesra','Kheir Eddine','Sidi Ali','Ain Boudinar','Bouguirat'],
  '28': ["M'Sila",'Bou Saâda','Ain El Melh','Sidi Aïssa','Ain El Hadjel','Magra','Berhoum','Maadid','Hammam Dalaa','Ouled Derradj'],
  '29': ['Mascara','Sig','Mohammadia','Ain Fares','El Ghomri','Matemore','Hachem','Bouhanifia','Tizi'],
  '30': ['Ouargla','Hassi Messaoud','Ain Beida','Touggourt','El Borma','Temacine','Sidi Slimane','Nezla','Zaouia El Abidia'],
  '31': ['Oran','Bir El Djir','Es Sénia','Arzew','Ain Turk','Gdyel','Hassi Bounif','Mers El Kebir','Sidi Chahmi','El Kerma','Boutlelis','Ain El Turk','Bethioua'],
  '32': ['El Bayadh','Boualem','Ain El Orak','Stitten','El Abiodh Sidi Cheikh','Mehara'],
  '33': ['Illizi','Djanet','In Amenas','Debdeb'],
  '34': ['Bordj Bou Arréridj','Ras El Oued','El Hamadia','Mansourah','Ain Taghrout','Bordj Ghedir','Bir Kasdali','Ouled Sidi Brahim'],
  '35': ['Boumerdès','Bordj Menaïel','Boudouaou','Khemis El Khechna','Thénia','Dellys','Naciria','Tidjelabine','Si Mustapha','Isser'],
  '36': ['El Tarf','Ben Mehidi','Bouteldja','Besbes','Ain El Assel','El Kala','El Aioun','Zerizer','Chihani'],
  '37': ['Tindouf'],
  '38': ['Tissemsilt','Ain Azzal','Theniet El Had','Beni Lahcene','Lazharia','Layoune'],
  '39': ['El Oued','Bayadha','Nakhla','Guemar','Kouinine','Reguiba','Hamraia','Taghzout','Magrane','Still'],
  '40': ['Khenchela','Ain Touila','El Hamma','Kais','Babar','Chechar'],
  '41': ['Souk Ahras','Sedrata','Merahna','Ain Zana','Ain Soltane','Mechroha','Bir Bouhouche'],
  '42': ['Tipaza','Ain Tagourait','Bou Ismail','Cherchell','Damous','Fouka','Kolea','Hadjout','Gouraya'],
  '43': ['Mila','Ferdjioua','Chelghoum El Aïd','Ain Mellouk','El Mechira','Tassadane Haddada'],
  '44': ['Aïn Defla','Miliana','Khemis Miliana','El Attaf','El Amra','Ain Torki','Boumedfaa'],
  '45': ['Naâma','Mecheria','Ain Sefra','Sfissifa','Tiout','Kasdir'],
  '46': ['Aïn Témouchent','Hammam Bouhadjar','El Malah','Sidi Benyebka','Ain El Arba'],
  '47': ['Ghardaïa','Berriane','El Guerrara','Metlili','Bounoura','El Atteuf','Mansoura','Guerrara'],
  '48': ['Relizane','Mazouna','Ain Tarik','Djidiouia','Sidi M\'Hamed Benali','Hamri','Mendes'],
  '49': ['Timimoun','Aougrout','Charouine','Deldoul','Ouled Said','Tinerkouk'],
  '50': ['Bordj Badji Mokhtar','Timiaouine'],
  '51': ['Ouled Djellal','Sidi Khaled','Ras El Miad'],
  '52': ['Béni Abbès','El Ouata','Kerzaz','Ksabi','Tabelbala'],
  '53': ['In Salah','Foggaret Ezzaouia','In Ghar'],
  '54': ['In Guezzam','Tin Zaouatine'],
  '55': ['Touggourt','Temacine','Megarine','El Allia','Nezla'],
  '56': ['Djanet','Bordj El Haouès'],
  '57': ["El M'Ghair",'Djamaa','Sidi Amrane','Still'],
  '58': ['El Meniaa','Hassi Gara','Issameur'],
}

export function getCommunesByWilaya(wilayaCode: string): string[] {
  return COMMUNES[wilayaCode] || ['Chef-lieu de wilaya']
}
